### ISSUE TITLE
selection.call, but returning the returned value.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#102]
This would make it more useful, e.g., as a transition factory. Unfortunately this would need to wait for 5.0 and could be a tricky update.

**Comment by curran** [comment]
To me <i>selection</i>.<b>call</b> is useful *only because* it's consistent in what it returns, and enables method chaining.

If <i>selection</i>.<b>call</b> returned the return value from the function, how is it (option A) any better than calling the function directly (option B)?

Option A:
```js
var returnValue = selection.call(someFunctionThatReturnsAThing);
```

Option B:
```js
var returnValue = someFunctionThatReturnsAThing(selection);
```

Also, the caller will need to know which functions return a new selection in order to follow D3's indentation convention correctly.

```js
selection
    .call(function1ThatReturnsNothing)
  .call(functionThatReturnsANewSelection)
    .call(function2ThatReturnsNothing);
```

**Comment by mbostock** [comment]
Yes, this change requires that any function you *selection*.call returns a meaningful value—that’s why this would be a breaking changing requiring a major version bump. This means whoever implements the functions you are calling will need to do a little more work (often adding `return selection;` at the end).

The advantage is that you will be able to *selection*.call a function that does something besides simply modify the current selection, and by extension be able to use method chaining for more interesting applications. For example, maybe your function computes a data join, appends & removes elements, and returns the new joined selection; or maybe it does *selection*.append and other goodness and returns the appended selection.

And yes, you’ll need to know what the function does—and what it returns—when you call it.

We could have two methods: one that returns the called function’s return value, and another that returns the current selection. (I could also imagine that the current selection is returned if the called function returns undefined… but that seems error-prone.) But I think for parsimony it would be better to have only a single method for this.

**Comment by curran** [comment]
Thanks for expanding on the idea here.

I'm working on this [d3-component](https://github.com/curran/d3-component) thing, and am using *selection*.call ubiquitously, where the callee returns a merged Enter + Update selection. This enables two "modes" of invocation, both of which are useful in different scenarios:

The "original selection level" mode (current behavior of *selection*.call), which supports adding multiple things to the same level of the DOM:

```js
// Components A, B, and C all end up as siblings in one DOM level.
selection
    .call(componentA)
    .call(componentB)
    .call(componentC)
```

The "one level deeper" mode, which is useful for first scaffolding out a new node using the General Update Pattern, then building out stuff within that new node:

```js
// Components B, and C end up as children of component A's DOM. 
componentA(selection)
    .call(componentB)
    .call(componentC)
```

Just for comparison, here's what those two "modes" would look like after the proposed change:


```js
// Components A, B, and C all end up as siblings in one DOM level.
componentA(selection);
componentB(selection);
componentC(selection);
```

The "one level deeper" mode now requires the introduction of a new variable.

```js
// Components B, and C end up as children of component A's DOM.
var componentAMergedEnterUpdate = selection.call(componentA);
componentB(componentAMergedEnterUpdate);
componentC(componentAMergedEnterUpdate);
```

Food for thought :smile:

**Comment by mbostock** [comment]
Just spit-balling here, but perhaps you could expose a new method on your components? So maybe calling a *component*.parent returns the parent (“original”) *selection*, while calling *component* returns the component’s selection? So you call *component*.parent if you want to stay on the same level, and *component* if you want to descend into the *component*.

```js
// “original selection level” mode
selection
    .call(componentA.parent)
    .call(componentB.parent)
    .call(componentC.parent);

// “one level deeper” mode
selection
  .call(componentA)
    .call(componentB.parent)
    .call(componentC.parent)
```

Alternatively, you could have *component* stay on the same level, and *component*.select to descend into the component:

```js
// “original selection level” mode
selection
    .call(componentA)
    .call(componentB)
    .call(componentC);

// “one level deeper” mode
selection
  .call(componentA.select)
    .call(componentB)
    .call(componentC)
```

The latter’s probably better since it makes the default to stay at the same level, and the word “select” hopefully makes it more obvious what is happening.

**Comment by curran** [comment]
Oooh I like it! The latter is quite elegant.

**Comment by AmatanHead** [comment]
I vote for implementing two separate functions for this. Mostly because there should be a way to call a function that returns something useless. For example, I sometimes do `selection.call(console.log)` to debug things.

In my projects I tend to monkeypatch this function:

```js
d3.selection.prototype.apply = d3.transition.prototype.apply = function () {
    const callback = arguments[0];
    arguments[0] = this;
    return callback.apply(null, arguments);
};
```

I also would like to see a function that returns the parent selection (something similar was described couple comments above). This way, generating complex html structures would be way simpler and cleaner.

Consider:

```js
createRows(selection) {
    const rows = selection.selectAll('.table__row').data(d => d.rows);
    
    rows.exit().remove();
    
    rows.enter()
        .append('div')
            .attr('class', 'table__row')
            .append('div')
                .attr('class', 'table__row__cell table__row__cell_metric_name')
                .back()
            .append('div')
                .attr('class', 'table__row__cell_group table__row__cell_group_values')
                .back()
            .append('div')
                .attr('class', 'table__row__cell table__row__cell_text')
                .back()
        .merge(rows)
            .select('table__row__cell_metric_name')
                .text(d => d.en_name || d.name)
                .back()
            .select('table__row__cell_group_values')
                .call(createValueCells)
                .back()
            .select('table__row__cell_text')
                .text(d => d.trailingText);
}

createValueCells(selection) {
    const cells = selection.selectAll('table__row__cell').data(d => d.values);

    cells.exit().remove();

    cells.enter()
        .append('div')
            .attr('class', 'table__row__cell');
        .merge(cells)
            .text(d => d.value);
}
```

would output something like this:

```html
<div class="table__row">
    <div class="table__row__cell table__row__cell_metric_name">Metric name</div>
    <div class="table__row__cell_group table__row__cell_group_values">
        <div class="table__row__cell table__row__cell_value">1</div>
        <div class="table__row__cell table__row__cell_value">2</div>
        <div class="table__row__cell table__row__cell_value">3</div>
    </div>
    <div class="table__row__cell table__row__cell_text">Whatever</div>
</div>
```

**Comment by davestaab** [comment]
I have a similar situation where I want to abstract out turning transitions on/off.

If I could return the transition instead of it always returning the original selection that would be nice.

```javascript
selectAll('.circles')
  .attr('r', 0)
  .call(addTransitions)
  .attr('r', 50)

function addTransitions (selection) {
    if (useTransitions) {
      return selection
        .transition()
        .duration(duration)
        .ease(ease)
    }
    return selection
  }
```

Now I  have to break out of chaining and it's ugly....
```javascript
addTransitions(
  selectAll('.circles')
  .attr('r', 0)
).attr('r', 50)
```

I might add a `callAdvanced` method to the prototype for my use case as suggested above by mbostock. ( as always, naming things is hard and I noticed Mike didn't suggest a name for this alternate call method. 😃 )

**Comment by Guema** [comment]
Idk if it's still planned, but i would personally LOVE this feature.

And yes, i just commented to say this.

**Comment by Guema** [comment]
Just a dump question about the discussion.
what if `.call` still return selection if callback in argument returns nothing, and returns returned value if returned value is not "undefined".

```
d3.selectAll("div")
    .enter()
    .call(foo) // returns the div selection in the pipe
    .call(bar); // returns the returned [] in the pipe

function foo(selection, i, n) {
    // do things
    // no return statment
}

function bar(selection, i, n) {
    // do things
    return [];
}
```

The only problem i see could be using it with this terrible ES6 "()=>" functions...
Maybe performances too, as i eared wrapping functions in conditions is not cool...
But if we consider people wrote callbacks without caring return value until now, i suppose it could limit compatibility break ?

**Comment by mbostock** [comment]
After ruminating on this for… well, a couple years… there are certainly enough applications where it’s useful for *selection*.call to return the current selection (rather than the return value) that we should retain the current behavior. It’s especially nice in conjunction with the new *selection*.join #194. We should a new method if we want this behavior.

**Comment by mbostock** [comment]
Closing to inactivity.

**Comment by NeonMika** [comment]
Are there any updates on

> We should [add] a new method if we want this behavior.

Has something like this been release in new d3 versions?

I am certain there are people out there (like me) that would like to have this behavior, no matter the function name.

If `call` should always return the original selection, another method could be introduced.
It kinda reminds me of a `map` function in functional-style programming - it takes a selection, might transform it (in my case appends new elements) and then return it.

Crazy example code:
```
mySelection.map(fnThatReturnsANewSelection)
           .call(fnThatReceivesTheSelectionReturnedByMap)
           .call(anotherFnThatReceivesTheSelectionReturnedByMapBecauseCallReturnsTheOriginalSelection)
```
