### ISSUE TITLE
Clarify whether d3.selection supports Nodes or only Elements

### ISSUE THREAD

**Issue by pallosp** [d3/d3-selection#103]
According to https://github.com/d3/d3-selection#selectAll `d3.selection` seems to support any Nodes. The documentation explicitly mentions `childNodes`. 

According to https://github.com/d3/d3-selection#selection_node `d3.selection` seems to ignore Nodes that are not Elements.

`d3.selectAll('p').insert(() => document.createTextNode('p'))` works and returns a selection consisting of TextNodes. `d3.selectAll('p').insert(() => document.createTextNode('p')).nodes()` returns the actual nodes.

`d3.mouse()` only accepts elements.

**Comment by pallosp** [comment]
`d3.select(document.createTextNode('')).attr('foo')` throws, therefore I assume that selections should only contain Elements.

**Comment by mbostock** [comment]
In practice, most selections consist of DOM elements. The word “node” and “element” is used interchangeably in the documentation and the interface, which I admit is confusing.

However, you can select anything you want, including arbitrary objects. So “node” and “element” more precisely refers to whatever object is selected. The *selection*.node method doesn’t do any type-checking on what is selected, and D3 methods in general do not type-check inputs; instead they rely on duck typing.

This implies that methods only work if the selected objects support the necessary methods. For example, *selection*.attr requires *element*.setAttribute, *element*.setAttributeNS,  *element*.removeAttribute and *element*.removeAttributeNS. So you can `d3.select(window)` and call *selection*.on on the resulting *selection*, but you can’t call *selection*.attr.

If you are interested in this subject, I suggest reading the following thread: https://github.com/tomwanzek/d3-v4-definitelytyped/issues/2
