### ISSUE TITLE
selection.data() function should take two key functions

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [d3/d3-selection#104]
I propose to extend the API for `selection.data(data)` to accept two different key functions: One to be applied to the `datum`, `index`, `nodes` of the `selection` element (think: old data), and one to be applied to the `datum`, `index`, `data` of the `data` array.

I find myself in the situation that I would like to modify the Ticks of an axis, depending on some data `data` that say is an array of objects
```
{ key: STRING, values: { value1: NUMBER, value2: NUMBER, flags: {flag1: BOOLEAN} }
```
using `flag1`.

The ticks, say for the `x` axis, have been drawn using the `key`s in `data` as domain.
Hence (as far as I can tell) they have data bound to them, namely precisely a `STRING` found under `key`.

Now I would like to bind data to the ticks such that I can access `flag1` of the corresponding datapoint, i.e. element of `data`.

One approach is to `selectAll` (x-) ticks and call `.data(data)` on the selection. The problem here is that not necessarily all elements of data are represented by a tick, hence the selection by index would just bind the first datapoints of `data` to the existing ticks, which is not what I want - I need the datapoints to correspond to the data bound to the ticks.

Hence the next iteration is to use a key function: This function will get called both on the tick element, and on the datapoints in `data`.
On the tick element, it could just look like this:

```
function(tickData) {return tickData;}
```

but for a datapoint of `data`, it might look like this:

```
function(dataPoint) {return dataPoint.key;}
```

So I don't seem to be able to write a function that picks up the right data in both cases and gives me the join I want.

It seems that the flexibility of being able to optionally supply a second function to seperate treatment of the datum coming from nodes of the `selection` on the one hand and the `data` array on the other hand would solve my problem. Possibly there are other use cases where this is beneficial?

Possibly somebody has an idea how to solve the above problem with already given methods?

**Comment by mbostock** [comment]
The recommended way of doing this is to write a conditional key function that somehow distinguishes between the old data and the new data. If you know that the old data is just numbers (because they represent the ticks created by d3-axis), and the new data is objects with a *d*.key property, you can say:

```js
function key(d) {
  return d.key || d;
}
```

This assumes that *d*.key value is also truthy. If you want to be a bit more strict, you could say:

```js
function key(d) {
  return d.key == null ? d : d.key;
}
```

Or even:

```js
function key(d) {
  return typeof d === "number" ? d : d.key;
}
```

**Comment by valentin-krasontovitsch** [comment]
Yes, indeed, that absolutely solves my problem.
Thank you very much for your time and help, I greatly appreciate it!
