### ISSUE TITLE
"styles()" method not found

### ISSUE THREAD

**Issue by callin2** [d3/d3-selection#118]
Apit reference : https://github.com/d3/d3-selection-multi/blob/master/README.md#selection_styles
but I can't find styles method in selection instance.

**Comment by curran** [comment]
Did you import https://github.com/d3/d3-selection-multi ? Note that `d3-selection` and `d3-selection-multi` are separate packages, and the methods from `d3-selection-multi` are not in `d3-selection`, and also not in the default D3 build.

**Comment by mbostock** [comment]
You are looking for [d3-selection-multi](https://github.com/d3/d3-selection-multi).
