### ISSUE TITLE
Allow d3.mouse() to optionally specify the related (source) event

### ISSUE THREAD

**Issue by diagramatics** [d3/d3-selection#121]
Heya. I've been trying to use d3 with Angular and instead of generating the elements and binding events through d3 I opted to use static markup in the Angular template and setting a `mousemove` event there. The problem is that when I execute a function in the event handler the source event reference becomes `null`, obviously since the called function has no context of the event.

Is it possible to get `d3.mouse()` to have an optional parameter to pass in the source event? I found that extracting https://github.com/d3/d3-selection/blob/master/src/point.js and using that explicitly works wondrous on my use case, so an option to expose `d3.point()` might be a viable one as well?

Thanks in advance!

**Comment by mbostock** [comment]
You’d need to use [d3.customEvent](https://github.com/d3/d3-selection/blob/master/README.md#customEvent) to set [d3.event](https://github.com/d3/d3-selection/blob/master/README.md#event) temporarily during the call to [d3.mouse](https://github.com/d3/d3-selection/blob/master/README.md#mouse).

I’d be okay exposing d3.point, though I think it should be renamed to d3.pointer before doing so. (d3.point is a little too generic, and d3.pointer matches nicely with the concept of pointer events as something that can apply to both the mouse and touch.)

**Comment by mbostock** [comment]
(Feel free to open a pull request exporting d3.pointer!)

**Comment by diagramatics** [comment]
Ah thanks a lot! I'll make a PR when I have the time to do that.
