### ISSUE TITLE
d3.mouse fails when sourceEvent is missing in Firefox

### ISSUE THREAD

**Issue by spanitz** [d3/d3-selection#122]
Here's the use case and code to reproduce:

```javascript
const brush = d3.brushX()
  .extent([[0, 0], [100, 100]])
  .on('brush', function() {
    const mouse = d3.mouse(this);
    // doing some stuff with mouse ...
  });

const g = svg.append('g').call(brush):

// ...

brush.move(g, [50, 70]); // <- fails
```

Firefox (currently 51.0.1) raises the following error on brush (initiated by brush.move())
```
TypeError: Value being assigned to SVGPoint.x is not a finite floating-point value.
```

See: https://github.com/d3/d3-selection/blob/v1.0.5/src/point.js#L6
In this case `point.x` will be assigned with `undefined`. Actually an early return like `if (!event) return;` would fix this issue.

Current workaround:

```javascript
.on('brush', function() {
  if (d3.event.sourceEvent) { // <- check if an user event exists
    const mouse = d3.mouse(this);
    // doing some stuff with mouse ...
  }
});
```

**Comment by mbostock** [comment]
If there is no sourceEvent for a brush event, then the position of he mouse is undefined, so this is the expected behavior. You should not assume that all brush events are user-driven, as they can be triggered by a programmatic call to *brush*.move; checking for the presence of a sourceEvent is the correct way to distinguish between these two cases and to avoid the execution of code that depends on the mouse position.

**Comment by spanitz** [comment]
That's exactly what I did: checking for the presence of `sourceEvent`; and that's ok for the above mentioned use case. But I'm wondering if the mentioned error or any other TypeError (as you doing little calc with `event. clientY` and stuff) could also raise in other situations. As you already said, all events shouldn't be treated as user-driven. So guarding the `point` calculation can't be as bad. ;)

**Comment by mbostock** [comment]
It is not supported to call d3.mouse when there is not a current user event. Yes, you could put internal guarding into d3.mouse to throw an error here, but it’s generally my philosophy to improve the documentation instead of trying to protect all the code against invalid usage.
