### ISSUE TITLE
Getting element size using selection.style

### ISSUE THREAD

**Issue by anderspitman** [d3/d3-selection#128]
I believe commit [`e7c72a6`](https://github.com/d3/d3-selection/commit/e7c72a68028ecba3db709e28de22f6a0b2f0ce81) may have broken my code, and I think it's because I've been relying on some brittle functionality. I probably need to find a more correct method for what I'm trying to accomplish. In order to create responsive d3 views, I've been setting my SVGs to use 100% of the available space, like this:

```javascript
var view = containerSelection.append("svg").style("width", "100%").style("height", "100%");
```

Then when I render the view (this is the part that feels especially hacky):

```javascript
var width = parseInt(view.style("width"));
var height = parseInt(view.style("height"));
```

And I use width and height for everything after that point.

Is there a more robust method to create d3 SVGs that are responsive to whatever parent you shove them in?

**Comment by mbostock** [comment]
The simple fix is to query the container rather than the SVG element you added:

```js
var width = parseInt(containerSelection.style("width"));
var height = parseInt(containerSelection.style("height"));
```

But it’d be cleaner to use [*element*.getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect):

```js
var rect = containerSelection.node().getBoundingClientRect(),
    width = rect.width,
    height = rect.height;
```

That should work on either the container or the SVG element.

**Comment by anderspitman** [comment]
That did it, thanks!

**Comment by jfsiii** [comment]
I, too, was bitten by this. While I appreciate making the API faster & more predictable, I do believe this was a breaking change and should have a corresponding API version bump.

Again, I see the rationale for the change, but the behavior changed in a way that breaks code depending on the existing behavior.
