### ISSUE TITLE
if data method's params is object, enter and exit method does't work

### ISSUE THREAD

**Issue by niki571** [d3/d3-selection#129]
I want to draw a pointer which will move as time goes. Now I remove the pointer before I redraw it as following code.
```
function drawPointer() {
   svg.select('g.pointer').remove();
   const pointerX = scale(new Date());

   const g = svg.selectAll('g.pointer')
                   .data([{ x: pointerX, y: 0 }], (d) => d);

   g.enter().append('g')
                 .attr('class', 'pointer').call(pointer);
}

drawPointer();
this.timer = window.setInterval(() => { drawPointer(); }, 1000 * 5);
```
But I feel it is not so elegant. I want to use exit method to remove the pointer as below.
```
function drawPointer() {
   const pointerX = scale(new Date());

   const g = svg.selectAll('g.pointer')
                   .data([{ x: pointerX, y: 0 }], (d) => d);

   g.enter().append('g')
                 .attr('class', 'pointer').call(pointer);
  g.exit().remove();
}

drawPointer();
this.timer = window.setInterval(() => { drawPointer(); }, 1000 * 5);
```
I read the source code, 
`keyValues[i] = keyValue = keyPrefix + key.call(node, node.__data__, i, group);`
I think before adding `keyPrefix` to data, we can get the data type. If it is object, `JSON.stringify(data)`. Otherwise, all of them are `$[object Object]`.

Is it practicable？

**Comment by mbostock** [comment]
This is the expected behavior. Your key function should return a string, not an object (or assume that the returned value will be string-coerced). I’ll edit the README to make this more clear.
