### ISSUE TITLE
Contradiction in documentation

### ISSUE THREAD

**Issue by wereHamster** [d3/d3-selection#130]
> Selections are immutable.

> If the exit selection is retrieved more than once after a data join, subsequent calls return the empty selection.

It appears that the second statement is wrong. I can call `.exit()` multiple times and it consistently returns a non-empty set.

**Comment by mbostock** [comment]
Right, the second statement is wrong and a holdover from earlier versions. Thank you for bringing this to my attention. I will push a fix to the README.
