### ISSUE TITLE
Should throw error if element does not exist

### ISSUE THREAD

**Issue by WhoAteDaCake** [d3/d3-selection#132]
Too often have I encountered an issue where d3 was not working, because i passed
```javascript
const id = 'idHere';
const elem = d3.select(id).append('svg');
```
Instead of 
```javascript
const id = 'idHere';
const elem = d3.select(`#${id}`).append('svg');
```
This could be avoided if a simple Error was thrown.

**Comment by mbostock** [comment]
Sorry, but I don’t think this is a good idea, especially given the current behavior. Empty selections are valid so it’s not an error for the given selector to not match any element, and you can use [*selection*.empty](https://github.com/d3/d3-selection/blob/master/README.md#selection_empty) or similar logic to handle the empty case if needed.

You might try proposing a d3.selectOne method to [d3-jetpack](https://github.com/gka/d3-jetpack), if you want something along these lines.
