### ISSUE TITLE
Add event as an optional parameter to mouse

### ISSUE THREAD

**Issue by rowanwork** [d3/d3-selection#148]
The `mouse` function doesn't seem to work in React 16 as it can't seem to find the source event:
```
// sourceEvent.js
var current = event, source;
// The below line throws: TypeError: Cannot read property 'sourceEvent' of null
while (source = current.sourceEvent) current = source;
```

Could `mouse.js` be changed to something like:
```
export default function(node, e = null) {
  var event = e || sourceEvent();
  if (event.changedTouches) event = event.changedTouches[0];
  return point(node, event);
}
```
Then in the react side I could call it like `mouse(node, e.nativeEvent)`.

Alternatively, `point.js` doesn't seem to be a named export and I have to import it like so:
`import point from 'd3-selection/src/point';`
 If point became a named export then I would be more comfortable calling `point(node, event)` directly.

**Comment by mbostock** [comment]
The error suggests a bundling problem; what is the value of d3.event when this error occurs? If d3.event is null, it is typically because D3 is being bundled by a bundler that does not preserve the live binding property of ES imports, and thus d3.event is always null. d3.event is set during the invocation of an event listener registered by *selection*.on.

At any rate, I’d support both of these changes: (1) allowing the *event* to be passed to d3.mouse, using d3.event if the *event* is falsey; and (2) exporting the `point` function as, let’s say, d3.clientPoint.

**Comment by rowanwork** [comment]
Thanks for the follow up.

I am using Create React App, so I don't have any control over the bundling (unless I eject...).

Not sure if this is the correct way of getting `d3.event`, but I have tried the following and it seems to be `null`:
```
import { select, event as d3Event } from 'd3-selection';
  //...
function handleMouseMove(event) {
  console.log(d3Event);
}
```

**Comment by mbostock** [comment]
Strange. I *think* that should work, provided that create-react-app has the default [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields) for webpack, which should prefer the module entry in d3-selection’s package.json, giving you a live binding to it’s `event` export. You might want to file a bug over on create-react-app?

**Comment by rowanwork** [comment]
OK thanks, just wanting to check something with you then before I log a bug with them.  This is probably a silly question, but your link to `resolve.mainFields` has the example `import * as D3 from "d3"`, but I am not doing this as I am only importing the d3 modules that I need, is that OK?

I am also not using d3 to append elements to the DOM, I am using react to add the lines, shapes, event handlers etc and I am only using d3 to generate the path info etc ([example](https://gist.github.com/danscan/aeea126a017d8ea0ed6bd4b6e19f4556#file-timeseriessparkline_v2-jsx)). Will this still be OK?

**Comment by mbostock** [comment]
You are doing what I recommend—importing the individual modules instead of the D3 default bundle.

If you are not using *selection*.on, then d3.event will always be null (even if your bundler is configured correctly). The only way to use d3.event is with *selection*.on. Maybe that’s the problem here?

**Comment by rowanwork** [comment]
That must be the problem then as I am using React to add the event handlers. 

Hopefully that doesn't invalidate my initial two proposals. If not, then I would be happy to attempt a PR for them.

Thanks for your help with getting to the bottom of this.

**Comment by mbostock** [comment]
Glad we figured it out. Yep, still on board with the proposed changes in https://github.com/d3/d3-selection/issues/148#issuecomment-338824454 if you care to send a PR.

**Comment by rowanwork** [comment]
That PR is from my other account. Please let me know if I have missed anything. Thanks

**Comment by mbostock** [comment]
On closer inspection, I don’t think we need both of these changes; d3.mouse(*node*, *event*) is pretty much identical to d3.clientPoint(*node*, *event*), so it’d be better to just have the latter. Please review #151.

**Comment by samal84** [comment]
For me it was the same reason as this: https://github.com/d3/d3-selection/issues/185#issuecomment-419474845

I'm using Yarn and it had added two versions of d3-select. I manually removed one from yarn.lock and then it worked.
