### ISSUE TITLE
Return `undefined` when calling `selection.datum()` on a null selection

### ISSUE THREAD

**Issue by bhousel** [d3/d3-selection#154]
Sometimes I want to check if some datum exists on a particular node.

```js
let d = d3.select('.mynode').datum();
```

If that node doesn't exist, d3 throws a `"TypeError: Cannot read property '__data__' of null"`.   
This is expected, so I need to guard the code like this:

```js
let thing = d3.select('.mynode');
let d = thing.size() && thing.datum() || undefined;
```

...but for convenience it would be great if `selection.datum()` would just not throw that error and return `undefined`.

If this sounds ok, I'm happy to write up a PR for it.

**Comment by mbostock** [comment]
Sorry, but I don’t agree; if a selection is empty, any method that depends on the selection being non-empty (such as *selection*.attr, *selection*.style, *selection*.datum) should throw an error rather than having special values for this case.

**Comment by mbostock** [comment]
If you do want to guard for this case, I also suggest using *selection*.empty to check whether a selection is empty, like so:

```js
let d = thing.empty() ? undefined : thing.datum();
```

**Comment by bhousel** [comment]
> Sorry, but I don’t agree; if a selection is empty, any method that depends on the selection being non-empty (such as selection.attr, selection.style, selection.datum) should throw an error rather than having special values for this case.

No problem, that makes sense when considering _selection_.datum as working like those other methods. Thank you for explaining the reasoning behind the decision!
