### ISSUE TITLE
The parent from select and selectAll different?

### ISSUE THREAD

**Issue by abrahamdu** [d3/d3-selection#158]
Hi,

I have a question regarding to the parent of select and selectAll.

My DOM looks like:

<svg id="example">
<g></g>
<g></g>
<g></g>
</svg>

But when I tried to pull the parent from the following two commands:

selectionDiv = d3.select("#example");
    selectionG = selectionDiv.select("g");
    selectionAllG = selectionDiv.selectAll("g");

![capture](https://user-images.githubusercontent.com/6256806/34238168-4f4232ee-e5ce-11e7-8bec-b091abc60b64.PNG)

The first part shows the console.log from selectionG and second part shows selectionAllG.

But the parent from selectionG is html while parent from selectionAllG is svg#example which is expected to my understanding. My thought is that parent of selectionG should be the same as selectionAllG. Any thought?

I only have one svg#example in my entire file.

Thanks,
Yi

**Comment by mbostock** [comment]
Please read [How Selections Work](https://bost.ocks.org/mike/selection/) for an explanation of select and selectAll. Thank you!
