### ISSUE TITLE
Upgrade to 1.3.0 release caused some downstream dependency issues

### ISSUE THREAD

**Issue by josh803316** [d3/d3-selection#160]
I'm not sure why issue below would happen as the result of a release change but I noticed ember build and test failures pointing to d3-selection dependency issues.... It only happened since the release change a couple of hours ago so I figured I would open an issue here just in case.  It could potentially be my own setup or an issue with d3 or ember-d3...
https://github.com/ivanvanderbyl/ember-d3/issues/46

**Comment by mbostock** [comment]
See https://github.com/ivanvanderbyl/ember-d3/issues/46#issuecomment-361100393.
