### ISSUE TITLE
Build error when using latest d3-selection version 1.3.0

### ISSUE THREAD

**Issue by GottfridL** [d3/d3-selection#161]
I am using d3 version 4.12.2 in my Ember application. When installing it I get the version 1.3.0 of d3-selection and I get the following error.

Build failed.
Build Error (Concat)
ENOENT: no such file or directory, open '{My_internal_filepath_structure_excluded\source_
map_concat-input_base_path-VM3etYBH.tmp\vendor\d3-selection\d3-selection.js'

If I downgrade to version 1.2.0 the build is successful. Somehow d3-selection 1.3.0 seems to not be compatible with d3 4.12.2.

**Comment by curran** [comment]
How could one reproduce this error?

**Comment by GottfridL** [comment]
I am trying to gather more information, so sorry for the short error information. Try out with referencing d3 version 4.2.2 in your application and let it install.

Following the npm install it seems to choose d3-selection version 1.3.0 due to reference in d3-brush since d3-brush references d3-selection major version 1. Am I right? In that case the bug is in d3-brush not specifying specific packages.

+-- d3@4.12.2
   +-- d3-brush@1.0.4
        -- d3-selection@1.3.0 
     -- d3-selection@1.2.0

**Comment by GottfridL** [comment]
Sorry I found out the problem. In my scripts I ran npm update --depth 4 which caused the d3-brush package to update to latest d3-selection eventhough d3 itself specified a specific older version. If anywhere it is a problem in npm update command.
But I would suggest d3-brush to reference more specific versions as well.

**Comment by GottfridL** [comment]
See https://github.com/ivanvanderbyl/ember-d3/issues/46#issuecomment-361100393
