### ISSUE TITLE
.local() on a selection?

### ISSUE THREAD

**Issue by IPWright83** [d3/d3-selection#167]
I'm wondering if it would be worth having `.local` as a function we can call directly on a selection? Partly to raise it's visibility and partly to make consumption of it easier. In my head I'm thinking it'd be nice to type:

```
const myLocal = d3.local();
d3.selectAll("g")
   .data(data)
   .enter()
   .append("g")
   .local(myLocal, d => d.text);
```

rather than:

```
const myLocal = d3.local();
d3.selectAll("g")
   .data(data)
   .enter()
   .append("g")
   // either of below
   .each((d, i, elements) => { myLocal.set(elements[i], d.text); });
   .each(function(d) { myLocal.set(this, d.text); });
```

Be happy to see if I can add this in, if it seems worth while.

**Comment by IPWright83** [comment]
I should probably include my particular use case. I'm using a text wrapping function, which is pretty expensive, and therefore only want to run it if my data's actually changed.

What I'm planning on doing is assigning the `old` data during the enter (and any updates where it changes) and then filtering out to only the modified items in my update. Something like this:

```
const myLocal = d3.local();
const join = d3.selectAll("g").data(data);

join.enter()
   .append("g")
   .each(function(d) { myLocal.set(this, d.text); })
   .merge(join)
   .filter(function(d) { return d.text !== myLocal.get(this); })
   .attr("text", d => d.text)
   .each(function(d) {
      myLocal.set(this, d.text);
      expensiveTextWrapFunction(this, d.text);
   });
```

It's nothing particularly hard - just improving some of the syntax.

**Comment by mbostock** [comment]
Did you see the documentation for [local.set](https://github.com/d3/d3-selection/blob/master/README.md#local_set) and in particular that you can use it with selection.property?

**Comment by IPWright83** [comment]
No I hadn't! That's useful, and I'll take a look at it.

At the moment I'm looking at writing an extension to the selection prototype to use `d3.local` and apply a filter, essentially allowing a `selection.hasChanged("text")` to just give me the elements where a particular property has changed.
