### ISSUE TITLE
Pass event objects to event handlers, please

### ISSUE THREAD

**Issue by gka** [d3/d3-selection#170]
The d3.event + ES6 bundler nightmare is no fun to work around. 

> _If you use Babel, Webpack, or another ES6-to-ES5 bundler, be aware that the value of d3.event changes during an event! An import of d3.event must be a live binding, so you may need to configure the bundler to import from D3’s ES6 modules rather than from the generated UMD bundle; not all bundlers observe jsnext:main._

I'd say it's one of the most basic assumptions in event driven programming that the event handler *somehow* gets the event object passed as argument. I don't care if it's the first or tenth argument, but please don't rely on any global `d3.event` or `window.event` sorcery.

**Comment by mbostock** [comment]
This would break everything, so I’m not going to do this for D3 5.0. I might consider it for a future major release.
