### ISSUE TITLE
Suggestion: require explicit update selection after join

### ISSUE THREAD

**Issue by echuber2** [d3/d3-selection#184]
When people are learning D3, I've noticed one of the common misunderstandings is that data() intrinsically returns what is the update selection, and then enter and exit must be selected from it. What I'll suggest would not be backwards compatible with current D3, but what if it were like this: data() returns a selection that is intrinsically empty, and then **update()**, enter(), and exit() must be used separately. This would make it clear what is being returned. It might also be a good idea to track whether update/enter/exit calls are mixed in the same chain _without_ using merge(), which is another common oversight.

**Comment by mbostock** [comment]
I appreciate the suggestion, but I’m not currently considering any major revisions to the data join API. If I do revisit the design in a major release I’ll consider your input. Thank you!
