### ISSUE TITLE
version 1.3.1 crash with d3-transition: transition is not a function

### ISSUE THREAD

**Issue by royipressburger** [d3/d3-selection#185]
Hi.

After updating to version 1.3.1 im getting error that `select(...).transition is not a function`
I manage to narrow it down to be something in version 1.3.1.
Nothing has changed im my code only this update. any ideas?

Here is the code. (webpack with react and d3-pack)
```js
    const sortedData = this.sortData(this.props.data);
    const dataSet = { children: sortedData };
    const nodes = hierarchy(dataSet).sum(d => d[this.props.valueFieldName]);
    const size = 800;
    const bubbleSizeScale = scaleSqrt()
      .domain([
        this.props.minValue,
        this.props.maxValue,
      ])
      .range([this.props.minRaduis, this.props.maxRaduis]);

    const bubbles = pack()
      .size([size, size])
      .radius(d => bubbleSizeScale(d.value))
      .padding(this.props.bubblePadding);

    const svg = d3Select('.container-124')
      .attr('viewBox', `0 0 ${size} ${size}`)
      .attr('width', size)
      .attr('height', size)
      .attr('class', 'bubble');

    const self = this;
    const node = svg.selectAll('.node')
      // Render the data acourding to the node id and value
      .data(bubbles(nodes).descendants(), d => `${d.data.id}-${d.data[this.props.valueFieldName]}`);

    const bubbleContainer = node
      .enter()
      .filter(d => !d.children)
      .append('g')
      .style('cursor', 'pointer')
      .attr('class', 'node')
      .attr('id', d => `a${d.data.id}`)
      .attr('transform', d => `translate(${d.x},${d.y})`);


    bubbleContainer
      .append('circle')
      .enter();

    svg.selectAll('circle')
      .attr('r', 1);

    bubbleContainer
      .append('text')
      .attr('dy', '7px')
      .attr('class', 'bubble-text-title')
      .style('text-anchor', 'middle')
      .style('opacity', 0)
    node.exit().remove();

    svg.selectAll('.node')
      .transition() //<-- Here it crashes.
      .duration(500)
      .attr('transform', d => `translate(${d.x},${d.y})`);

    svg.selectAll('circle')
      .transition()
      .duration(200)
      .attr('r', d => d.r);

    // Wait for bubbles to render then show the text
```

**Comment by curran** [comment]
@royipressburger This issue has to do with the way you are importing and bundling your code, not your code itself. Can you share a minimal project that would enable others to reproduce the error?

**Comment by royipressburger** [comment]
@curran Thanks for the response. 
[here](https://github.com/royipressburger/uglify-js-treeshake-issue/tree/d3-selection-transitio) is a repo that reproduce the issue.

The issue currently installed with `d3-selection@1.3.1` You will see that running `yarn start` will cause the issue. 
After that you can downgrade the version to `1.3.0` and all works good. 

Let me know if you need more info.
Thanks ahead

**Comment by curran** [comment]
Thanks for taking the time to post a full example! I am able to reproduce the issue at hand.

From [D3 Custom Bundle II](https://bl.ocks.org/mbostock/97557a39b4bfc8229786c8bccb54074d):

>Note that you _must_ also import selection from d3-selection; otherwise, Rollup doesn’t know that it needs to include the imported code from d3-transition.

I thought perhaps the same is true of Webpack and tried importing `selection` as well, like this:

```
import { selection, select as d3Select } from 'd3-selection';
import 'd3-transition';
```

Unfortunately this does not resolve the issue, and `selection.transition` is still not defined.

I can also confirm that `selection.transition` _is_ defined after reverting to

```
    "d3-selection": "1.3.0",
    "d3-transition": "1.1.3",
```

**Comment by royipressburger** [comment]
Good to know you are able to reproduce :), thanks for the help

**Comment by mbostock** [comment]
I spent a little time investigating this issue, but I didn’t discover anything. Unfortunately, I can’t provide support for code outside of D3, including bundlers such as Webpack; I suspect there’s an issue here in how your bundler is consuming D3 code. The most likely cause is a misconfiguration, but I don’t know for sure, sorry! If you can isolate the bug to D3, I’d be happy to look further.

**Comment by royipressburger** [comment]
Sucks :), I will try to figure it out with webpack and if ill find a solution ill update here.
Thanks for your time

**Comment by leon** [comment]
I'm getting the same error, and I think @edmorley was on to something.
I'm using d3 with angular 6 / typescript and am only importing the d3 libraries I use.

My package.json that caused the error was pinned to all the latest versions.

```
"d3-drag": "1.2.3",
"d3-scale": "2.1.2",
"d3-selection": "1.3.2",
"d3-time-format": "2.1.3",
"d3-transition": "1.1.3",
"d3-zoom": "1.7.3",
```

But if I changed them to only include 1 or 2

```
"d3-drag": "1",
"d3-scale": "2",
"d3-selection": "1",
"d3-time-format": "2",
"d3-transition": "1",
"d3-zoom": "1",
```
Then my code works.

I think it has to do with how webpack / angular compiler packages the files into different modules.
since we use `import 'd3-selection'` it doesn't know where .transition() and .interrupt() is used and doesn't know in which module it should include it.

**Comment by adaykin** [comment]
I'm running into this issue too, I get the error message "ERROR TypeError: node.transition is not a function" when using the ngx-charts library. Here's my package.json:

{
  "dependencies": {
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.10",
    "@angular/core": "^6.1.10",
    "@angular/forms": "^6.1.10",
    "@angular/http": "^6.1.10",
    "@angular/platform-browser": "^6.1.10",
    "@angular/platform-browser-dynamic": "^6.1.10",
    "@angular/router": "^6.1.10",
    "@angular/upgrade": "^6.1.10",
    "@ng-bootstrap/ng-bootstrap": "^3.2.2",
    "@swimlane/ngx-charts": "^9.1.1",
    "@types/chart.js": "^2.7.38",
    "@types/codemirror": "0.0.56",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.7.3",
    "chartjs-plugin-datalabels": "^0.1.0",
    "classlist.js": "^1.1.20150312",
    "codemirror": "^5.40.2",
    "core-js": "^2.5.7",
    "d3": "^4.13.0",
    "d3-selection": "^1.3.0",
    "intl": "^1.2.5",
    "jquery": "^3.3.1",
    "popper.js": "^1.14.3",
    "primeng": "^5.2.7",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "safe-pipe": "^0.3.0",
    "svgxuse": "^1.2.4",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler": "^6.1.10",
    "@angular/compiler-cli": "^6.1.10",
    "@types/d3": "^5.0.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^7.10.0",
    "codelyzer": "^4.0.0",
    "enhanced-resolve": "3.3.0",
    "jasmine": "^2.99.0",
    "jasmine-core": "^2.99.1",
    "jasmine-spec-reporter": "^3.2.0",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "lato-font": "^3.0.0",
    "ng2-file-upload": "^1.2.1",
    "node-sass": "^4.9.3",
    "protractor": "^5.4.1",
    "ts-node": "^2.0.0",
    "tslint": "^5.0.0",
    "typescript": "^2.7.2",
    "webpack-sources": "^1.3.0"
  },
  "scripts": {
    "build": "ng build --prod --progress=false",
    "build-watch": "ng build --dev --watch --verbose",
    "clean": "rimraf \"./target/classes/static/*\"",
    "test": "ng test --single-run",
    "test-watch": "ng test"
  }
}

**Comment by ramtob** [comment]
Does anyone has a solution? TIA

**Comment by royipressburger** [comment]
@ramtob a quick solution will be to downgrade `d3-selection` to version `1.3.0`.
Unfortunately I stoped looking into this problem cause it occur to me with `d3-hierarchy` and `pack` layout. 
I moved to `d3-force` and I had no issue with the `selection` versions

**Comment by ramtob** [comment]
@royipressburger Thanks for the input. Actually I did try (among other things) to downgrade `d3-selection` to 1.3.0, but, at least in my case, the problem persisted.. After all, we don't seem to know yet what change in `d3-selection` is causing the problem, if any.

**Comment by lostobject** [comment]
I am also seeing this and a downgrade of `d3-selection` did not help. I found a partial workaround which is to create a transition object from the root element, then select from that object, eg:
```typescript
d3.transition()
      .select('.value')
      .attr('width', (() => newValue + '%' ))
      .ease(easeExpInOut);
```
In my case this does not really help though since these are angular components and there are many on the page. I only want to transition a single one.

**Comment by Cygnusfear** [comment]
This fixes the issue for me: https://github.com/d3/d3-zoom/pull/161

**Comment by Bijan-Ghasemi-Afshar** [comment]
I had the same issue.
In my case, the solution was to simply use npm for package management, and it worked without pinning any version of the package. 
It seems to me it might be an issue with yarn itself (maybe a new update).
Hopefully this solution is helpful to some extend.

**Comment by LeeKevin** [comment]
As @edmorley mentioned, this was an issue due to multiple versions of d3-selection in the `yarn.lock`.

I had to add the following to my `package.json`:

```
    "resolutions": {
        "d3-selection": "1.3.0"
    }
```

Removed the `yarn.lock` file and then ran `yarn`

**Comment by DavidODonovan** [comment]
I had the same problem using create-react-app which relies on webpack. I copied a d3 class I created in an old app, which worked fine in its original location, but inside the new app I got the error 'selection.attr.transition is not a function'. The solution was to explicitly import transition from d3 like so; `import { transition } from 'd3-transition'; `  After doing that the selection.transition works as expected.

**Comment by coocooooo** [comment]
fix this issue by register `d3.selection.prototype` manually

```javascript
import selection_interrupt from '../../node_modules/d3-transition/src/selection/interrupt'
import selection_transition from '../../node_modules/d3-transition/src/selection/transition'
d3.selection.prototype.interrupt = selection_interrupt
d3.selection.prototype.transition = selection_transition
```

**Comment by Crashillo** [comment]
Even doing what @coocooooo says, the context is missing when you chain the methods, for instance:

```js
this.svg.selectAll("rect")
.attr("width", d => /* d has value */))
.transition()
.duration(1000)
.attr("width", d => /* d is undefined */)
```
After transition, there's no selection. So you need to append:
```js
...
.duration(1000)
.selectAll("rect")
.attr("width", d => /* d is defined */)
```
... what it's kinda harsh

**Comment by himz08** [comment]
> ...
> import 'd3-transition' 
> ...

Thanks. I was having the same problem but after importing this It resolved now. 
Everyone, Please make sure that you are importing the d3-transition

**Comment by sheikhsameer1609** [comment]
I had the similar issues when I used it with ngx-charts, with following versions
```
   "@swimlane/ngx-charts": "^8.1.0",
    "d3": "4.7.4"
```
It turned out to be due to transitive dependencies. Following changes worked out for me:
1. Reverted back my package-lock.json to the working one
2. Added d3-selection and d3-transition explicitly in my package.json
```
    "d3-selection": "^1.1.0",
    "d3-transition": "^1.3.2"
```
3.` npm install `

**Comment by matthewma7** [comment]
I had the issue multiple times, and it is true that it is caused by the presence of multiple versions of d3-selection (also d3-transition?).
I manually edited yarn.lock to consolidate multiple versions of d3-selection into one and it solved the issue.

```
d3-selection@^1.1.0, d3-selection@^1.3.0, d3-selection@^1.4.1, d3-selection@^1.4.2:
  version "1.4.2"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.2.tgz#dcaa49522c0dbf32d6c1858afc26b6094555bc5c"
  integrity sha512-SJ0BqYihzOjDnnlfyeHT0e30k0K1+5sR3d5fNueCNeuhZTnGw4M4o8mqJchSwgKMXCNFo+e2VTChiSJ0vYtXkg==
``` 
What my yarn.lock entry for d3-selection looks like after my manual consolidation.

**Comment by coreation** [comment]
> fix this issue by register `d3.selection.prototype` manually
> 
> ```js
> import selection_interrupt from '../../node_modules/d3-transition/src/selection/interrupt'
> import selection_transition from '../../node_modules/d3-transition/src/selection/transition'
> d3.selection.prototype.interrupt = selection_interrupt
> d3.selection.prototype.transition = selection_transition
> ```

This solved it for me, thanks so much! @coocooooo

**Comment by gameplaycoder** [comment]
yarn upgrade -i fixed my issue.

**Comment by peterpeterparker** [comment]
Above @matthewma7 solution worked for me too, thanks. I upgrade all my components to use the same `d3-transition`version, respectively v3, and it solved the issue.
