### ISSUE TITLE
Suspect memory leak when update frequently in realtime

### ISSUE THREAD

**Issue by dragonsoft-cara** [d3/d3-selection#196]
Hi there,
I found memory leak when using exist().remove() and append() to dynamically update digram.
Could any one help to see if there's any wrong in my code or is this an issue with d3, I'm using version 3.x.

<img width="1182" alt="screen shot 2018-11-26 at 10 19 44" src="https://user-images.githubusercontent.com/7014317/48989534-a5c5e180-f165-11e8-98fb-83c700404fe6.png">

Here's the demo:
[JSBin](https://jsbin.com/zakitel/edit)
[Devtool friendly](https://output.jsbin.com/zakitel#)

The main code to update diagram:
```javascript
    var letters = d3.select('svg').selectAll('text').data(vowelsAndNums, function(d) {
  		return d;
  	});

    letters.exit().remove();

    letters.attr('x', function(d,i) { return i*15; });

    letters.enter().append('text')
    	.text(function(d) { return d; })
    	.attr('x', function(d,i) { return i*15; })
    	.attr('y', 15);
```

**Comment by mbostock** [comment]
I don’t support D3 3.x anymore, sorry. I’m aware of a memory leak with event listeners #189 (https://github.com/d3/d3-selection/issues/186#issuecomment-419498459), but that shouldn’t apply in this example since you’re not using *selection*.on.
