### ISSUE TITLE
Performance considerations between data binding with and without key

### ISSUE THREAD

**Issue by pushshift** [d3/d3-selection#198]
I have looked online and also have viewed the source code for the latest version (5.7.0) but need some guidance for performance. There are two main ways to add data -- one is just passing a data array and the other is passing a data array with a key function to specify a key for each object in the array.

Without specifying a key, if I have a visualization that always has 5,000 elements, I assume I have to pass a data array with 5,000 elements each time (even if only a couple objects in the array have actual data changes since it will default to using the index location to compute enter, update, exits, etc.)

When specifying a key, I can pass a smaller array since the key function allows d3 to match up the data in the array with existing nodes (or create new ones if needed, etc.)  So instead of passing in an array of 5,000 elements each time, I can pass in a much smaller array for only the elements that I need updated.

Internally, how does D3 handle this difference? Are there performance benefits in using a data key function?  My guess is that using a key would yield faster performance for large data arrays where only a couple elements change now and then since without the key function, it would need to iterate over the entire array each time there is an update (even if for only one element).

Thank you Mike -- excellent work!

**Comment by mbostock** [comment]
Closing as a support question rather than an issue. Sorry I didn’t reply.
