### ISSUE TITLE
d3.create does not allow svg elements to be created with the correct namespace.

### ISSUE THREAD

**Issue by redmagic** [d3/d3-selection#199]
https://github.com/d3/d3-selection/blob/9ffa69f363b5ee9af2171879d798091eab68def0/src/create.js#L5

Because the creator is always called in the context of the html element, the called creator will always use the html namespaceUri and therefore make it impossible to `d3.create` svg elements with the correct namespace. The dom inspector will show the elements, but they will not be rendered because the namespace specific attributes are not applied. (So they will stay size 0 and no fill or stroke)

**Comment by mbostock** [comment]
Per the README, you need to specify the [namespace](https://github.com/d3/d3-selection/blob/master/README.md#namespace) explicitly when using d3.create because it is necessarily context-free (and thus uses the default HTML namespace).

For example:

```js
d3.create("svg") // equivalent to svg:svg
d3.create("svg:svg") // more explicitly
d3.create("svg:g") // an SVG G element
d3.create("g") // an HTML G (unknown) element
```

**Comment by redmagic** [comment]
Ah, I see. Thanks for clarifying Mike.
