### ISSUE TITLE
Commit  146af5d caused error: node.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by SeanBarryUK** [d3/d3-selection#201]
I have a chart which I noticed was broken today. The error message was `node.compareDocumentPosition is not a function`

After ensuring that absolutely nothing else had changed in my application, I checked out the file that was throwing the error and isolated it down to `order.js`. I noticed that there was a commit 146af5da2ed1bba5246e1e6a4d930f8c3d0adc5c that changed this exact line in the last few days and realised this may be the issue.

Also, because `d3` depends on `d3-selection` and it uses a `^` in the version number, this broke in production without us changing anything.

I've managed to temporarily fix this by implementing a resolution to `package.json` to lock the `d3-selection` dependency version to `1.3.1` and this has worked.

**Comment by mbostock** [comment]
It looks like you’re trying to run *selection*.order on something that’s not a DOM element.

**Comment by SeanBarryUK** [comment]
`selection.order` is being called by this chunk of code:

```   const bottomAxis = this.state.svg
      .select(`g.${ CLASSES.BOTTOM_AXIS }`)
      .call(xAxis)
      .attr('stroke-width', '0')
      .attr('transform', `translate(0,${ height - CHART_Y_OFFSET })`);```

There was no issue with this until the commit?

**Comment by fallax** [comment]
A simple example that reproduces this problem:
https://observablehq.com/@fallax/d3-selection-issue-201-example

**Comment by mbostock** [comment]
The problem with that notebook is that you are returning the enter selection from the join’s enter method; you need to return a materialized selection instead (typically the result of calling selection.append or selection.insert on the enter selection).

**Comment by fallax** [comment]
Thanks! Using that information I was able to debug my more complex use of join.

**Comment by fallax** [comment]
@methnen Unfortunately I can't find my fix anymore and my original broken example appears to work fine now. I suspect that you're probably experiencing a different issue to mine but which causes the same error to be output. If you're able to post a version of your code that's broken, perhaps I or someone else might be able to suggest something?

**Comment by methnen** [comment]
Hey!, thanks for the reply, I actually figured it out a bit ago, something about how d3 was selecting an element that wasn't behaving the way I thought it would, just required tweaking the code to select the element first then make changes to it at a later point if I remember correctly.

**Comment by ggojedap** [comment]
> The problem with that notebook is that you are returning the enter selection from the join’s enter method; you need to return a materialized selection instead (typically the result of calling selection.append or selection.insert on the enter selection).

Following this comment, I found:

```
// it works
.join(
  enter => enter
    .append("path")
    .attr("class", "item")
    .attr("fill", "red")
    .attr("d", arc)
)

// it does not work
.join(
  enter => { 
    enter
      .append("path")
      .attr("class", "item")
      .attr("fill", "red")
      .attr("d", arc);

    return enter;
  }
)

// it works!
.join(
  enter => { 
    let sel = enter
      .append("path")
      .attr("class", "item")
      .attr("fill", "red")
      .attr("d", arc);

    return sel;
  }
)
```

So, with the last alternative, it is possible to do custom changes to selection, append new svg sub-items, etc.
