### ISSUE TITLE
Documentation on selection.join refers to broken Observable notebook.

### ISSUE THREAD

**Issue by altocumulus** [d3/d3-selection#203]
The [selection.join Observable notebook ](https://beta.observablehq.com/d/6c522dda5dd9daa3) linked to from the documentation is broken as it still uses v5.7.0. This breaks all calls to `selection.join()` in that notebook.

**Comment by mbostock** [comment]
That notebook uses the latest d3@5, so if you clear your cache and reload, it should work.
