### ISSUE TITLE
d3 event is null

### ISSUE THREAD

**Issue by PierreCapo** [d3/d3-selection#212]
Hello !
I'm currently using d3 submodules instead of the global d3 in my current project in order to take the minimum size needed.

I have an issue being that when I use d3 submodules, when I try to zoom I got
`Uncaught TypeError: Cannot read property 'transform' of null`

And d3 submodules import is like this:
```JS
import { hierarchy, stratify, tree, treemap } from "d3-hierarchy";
import { event as currentEvent, select, selectAll } from "d3-selection";
import { zoom } from "d3-zoom";
```

Strangely, if I use the entire d3 library, it works well. Since I'm using Webpack, I've checked this [link](https://stackoverflow.com/questions/36887428/d3-event-is-null-in-a-reactjs-d3js-component/40304080#40304080), but as you can see I've taken care of renaming my `event` import already.

Here is a reproducible demo for showing when it is working (d3-global branch) and when it is not working (d3-submodules branch): https://github.com/PierreCapo/treeviz/pull/14/files

**Question : How can I make d3 event work by using `d3-selection` submodule ?**

Thanks in advance :)

**Comment by PierreCapo** [comment]
Fixed.
Although a bit ugly, I've had to do:

```js
// ./customD3.js

import { hierarchy, stratify, tree, treemap } from "d3-hierarchy";
import { event, select, selectAll } from "d3-selection";
import { zoom } from "d3-zoom";

export default {
  hierarchy,
  stratify,
  tree,
  treemap,
  select,
  selectAll,
  event,
  zoom,
};
```

And then in my file :

```js
// ./main.js
import * as d3 from "d3-selection";
import customD3 from "./d3";

// rest of the code

```

**Comment by StTronn** [comment]
v6 of d3 has no event export in [d3-selection/src/index.js](https://github.com/d3/d3-selection/blob/master/src/index.js).
