### ISSUE TITLE
Surprising behavior of `.join(string)`

### ISSUE THREAD

**Issue by harold** [d3/d3-selection#213]
First, let me express my thanks for d3, it's a total blast and I've enjoyed it for years. I have used it in both my personal and professional life and it has always been great. I really appreciate it.

See: https://jsfiddle.net/70u8z2vq/

Which has JS:
```
d1 = [0]
d2 = [0, 1]

function makeCX(d) {
  console.log("Calling makeCX")
  return 20 * d;
}

function slow(d) {
  d3.select("svg#slow-drawing")
    .selectAll("circle")
    .data(d)
    .join("circle")
    .attr("cx", makeCX)
    .attr("r", 10)
}

function fast(d) {
  d3.select("svg#fast-drawing")
    .selectAll("circle")
    .data(d)
    .join(enter => enter.append("circle")
                        .attr("cx", makeCX)
                        .attr("r", 10))
}

console.log("-----------------")
console.log("Slow:")
console.log("First:")
slow(d1)
console.log("Second:")
slow(d2)

console.log("-----------------")
console.log("fast:")
console.log("First:")
fast(d1)
console.log("Second:")
fast(d2)
```

The difference between `slow` and `fast` is that `slow` calls `.join` with a string and `fast` calls `.join` with a function.

When adding new data (e.g., when calling `slow(d2)`),  `slow` ends up calling `makeCX` for both the old data and the new data. Where `fast(d2)` only calls `makeCX` on the new data. So, in this particular case, `fast` calls `makeCX` one fewer time than slow.

However, in general, when adding data points one at a time this can be the difference between a runtime of `O(n^2)` and `O(n)`. :eyes: 

I think I sort of expected `.join(string)` to be equivalent to `.join(x=>x.append(string)...)`, but it seems to not be. Is this intended? And is there documentation somewhere about the different behaviors of `.join` under different argument type conditions?

**Comment by mbostock** [comment]
*selection*.join(*string*) is very much not the same as *selection*.join(*enter*); the latter only handles the enter selection case, whereas the former performs a general update that additionally handles *update* and *exit*. So this:

```js
d3.select("#slow-drawing")
  .selectAll("circle")
  .data(d)
  .join("circle")
    .attr("cx", makeCX)
    .attr("r", 10)
```

Is equivalent to this:

```js
d3.select("#slow-drawing")
  .selectAll("circle")
  .data(d)
  .join(
    enter => enter.append("circle"),
    update => update,
    exit => exit.remove()
  )
    .attr("cx", makeCX)
    .attr("r", 10)
```

The big difference between the “slow” and “fast” paths are that:

* The slow path sets the cx and r attributes on updating circles (not just entering).
* The slow path removes exiting circles.

**Comment by harold** [comment]
Thank you, I learned a lot.

I would like to help by updating the documentation. Is the top-level README of this repo the source of truth for the docs? If so, i could make a PR. If not, let me know where I can contribute.

I appreciate you and this library very much.

**Comment by mbostock** [comment]
The README is the official API reference, but we’re developing more human-friendly documentation over on Observable: https://observablehq.com/collection/@d3/d3-selection

**Comment by harold** [comment]
Super! Thanks again. :bowing_man:
