### ISSUE TITLE
relative coordinate problem in point.js

### ISSUE THREAD

**Issue by frameworker2019** [d3/d3-selection#227]
According to the problem [here](https://github.com/d3/d3-brush/issues/60) I found out, that I can change the behavior in the point.js routines as an instant workaround. 
If a D3 chart makes use of an brush **and ** the SVG of the chart element is embedded by a surrounding DIV with an explicite width, mouse clicks will not be interpreted correctly in Firefox or  Edge. In Chrome it works perfectly.
I changed the code like this to achieve that it works in FF and Edge, but lose functionality with Chrome:

```
function reverseTraversal(node,targetTagName) {
    var p = node;
    while(p.tagName != targetTagName) p = p.parentNode;
    return p;
}

function point(node, event) {
  var svg = node.ownerSVGElement || node;

  if (svg.createSVGPoint) {
    var point = svg.createSVGPoint();
    var p = reverseTraversal(node,"DIV");
    var rect = p.getBoundingClientRect();
    point.x = event.clientX + rect.width, point.y = event.clientY;
    point = point.matrixTransform(node.getScreenCTM().inverse());
    return [point.x, point.y];
  }

  var rect = node.getBoundingClientRect();
  return [event.clientX - rect.left - node.clientLeft, event.clientY - rect.top - node.clientTop];
}

```
As you can see, I have to traverse backwards until the closest DIV will be reached, get the bounding  and **add** its width to the clientX coordinate.
Without adding the fixed width, the brush is unusable in the particular case.

To get working with all the browsers, maybe a switch is necessary.

**Comment by mbostock** [comment]
D3 is not a compatibility layer, so generally speaking we do not incorporate workarounds for bugs in specific browsers. Sorry!
