### ISSUE TITLE
Cannot create svgpoint from a keyboard event in Firefox

### ISSUE THREAD

**Issue by dplassgit** [d3/d3-selection#237]
In [point.js](https://github.com/d3/d3-selection/blob/master/src/point.js#L6) it assumes that the `event` has defined `clientX` and `clientY` fields. But, if the event is a keyboard event it will not have those fields. Chrome is OK with assigning undefined to the field, but Firefox throws an exception:

```
TypeError: Value being assigned to SVGPoint.x is not a finite floating-point value.
```

**Comment by mbostock** [comment]
d3.clientPoint isn’t supposed to be passed a KeyboardEvent. It expects a [MouseEvent](https://www.w3.org/TR/DOM-Level-3-Events/#interface-mouseevent) or a [Touch](https://www.w3.org/TR/touch-events/#idl-def-Touch).
