### ISSUE TITLE
selection.selectChildren() to select immediate children

### ISSUE THREAD

**Issue by adumesny** [d3/d3-selection#243]
Would be nice to have a `selection.selectChildren()` (which could take for example 'g' for immediate node instead of all nested g, or empty for '*') shortcut for what might be **very common** - see https://stackoverflow.com/questions/20569670/d3-selector-for-immediate-children

Right now I had to research this and do this in Typescript (complains in Typescript even with latest @types/selection (so have to cast to `any` - yuck)
```js
this.container.selectAll(function() {return this.children;} as any)
````
(where container is selection of my svg root).

see discussion in #63 as well.

**Comment by mbostock** [comment]
First pass: #244.

**Comment by adumesny** [comment]
that's great. thank you.

**Comment by adumesny** [comment]
hey thanks for adding test cases and fixes. What is the likelihood of getting this a in release soon ?
I presume I can sync to a newer d3-selection than what d3 v5.16 gets me

**Comment by Fil** [comment]
Fixed in https://github.com/d3/d3-selection/commit/04e9e758c80161ed6b7b951081a5d5785229a8e6
