### ISSUE TITLE
How to add method for grouped selection?

### ISSUE THREAD

**Issue by nstrayer** [d3/d3-selection#250]
A simple question relating to the project structure that I have not been able to figure it out for the life of me. 

If I want to add a method to `selection` that works on both plain selections and grouped selections how do I do that?

As an example I have this function for short-handing transitions:

```js
d3.selection.prototype.move_to = function ({ x = 0, y = 0 }) {
  const eval_pos = function (p) {
    if (typeof p === "function") {
      return p(this.datum());
    } else {
      return p;
    }
  };
  return this.attr("transform", `translate(${eval_pos(x)},${eval_pos(y)})`);
};
```

It works great on simple selections. E.g. 
```js
svg.select('g').move_to({x:margin.left,y:margin.top});
```

But not on grouped selections:
```js
svg.selectAll('g.chart_elements').move_to({x:x_pos,y:y_pos});
```

I tried adding the prototype to `d3.selectionAll` but that didn't work either. 

Clearly I am attaching the prototype to the wrong object but I can't figure out what the correct object type is as I only see one call to the prototype assignment [here](https://github.com/d3/d3-selection/blob/master/src/selection/index.js#L44-L77). 

It looks like `Selection` is the proper object but I don't see that getting exported as its prototypes just get merged with `selection` and then `selection` is exported. Is this correct and there's no way to add a prototype to the group selection when operating on the bundled code?

Thanks and I hope this is the appropriate area for this question!

Best,
Nick

**Comment by mbostock** [comment]
Is `p` intended to be the argument to the move_to method in your code?

**Comment by nstrayer** [comment]
`p` for the position. Aka if the method is invoked with a function like

```js
my_els_w_data.move_to({x: d => d.x, y: d=>d.y});
```

it will work. Not sure if that's the proper way to do it.

**Comment by mbostock** [comment]
So you want to allow *x* and *y* to be specified as separate arguments? You might instead consider something like this:

```js
selection.moveTo(d => ({x: d.x, y: d.y}))
```

Or more simply, since *d* is already in the right shape:

```js
selection.moveTo(d => d)
```

This could then be implemented as:

```js
function translate({x, y}) {
  return `translate(${x},${y})`;
}

function translateFunction(p) {
  return function() {
    return translate(p.apply(this, arguments));
  };
}

d3.selection.prototype.moveTo = function(p) {
  return this.attr("transform", (typeof p === "function"
    ? translateFunction
    : translate)(p));
};
```

If you want *x* and *y* to be specified as separate functions, you have to decide whether you want to compute all the *x*-values first and then all the *y*-values, or if you want to interleave the computation. But I think it’s simpler if you only allow the function to be at the top level, rather than allowing an object-of-functions.

**Comment by nstrayer** [comment]
Turns out my problem was not what I thought it was. I'll elaborate here in case anyone else goes down a similar rabbit hole. 

I was getting the error `sel.move_to... is not a function` but it turns out that the error was coming from my attempt to do `this.datum()` _within_ the new prototype on the group selection. When the selection is a group `.datum()` obviously wouldn't mean anything. The error was just cut-off so it looked like it was saying the problem was the prototype didn't exist. 

Because of that I also realized a bunch of other mistakes in the code I pasted. I got everything working as originally intended with this modification: 

```js
d3.selection.prototype.move_to = function({ x = 0, y = 0 }) {
  this.each(function(d) {
    const x_pos = typeof x === "function" ? x(d) : x;
    const y_pos = typeof y === "function" ? y(d) : y;
    d3.select(this).attr("transform", `translate(${x_pos},${y_pos})`);
  });

  return this;
};
```

I agree that it's probably ideal to have the x-y position come from a single function call rather than two, but in this case I am almost always just specifying a single direction to translate and so it was less cumbersome to do `sel.move_to({x: d => d.x})` than `sel.move_to(d => ({x: d.x, y: 0}))`. 

I have implemented what I was attempting to get across in [this observable notebook](https://observablehq.com/@nstrayer/adding-a-method-do-grouped-selection) for people in the future with similar desires. 

Thanks for being patient with me asking a question that didn't make any sense!

**Comment by mbostock** [comment]
If that’s what you want, you can simplify like so:

```js
d3.selection.prototype.move_to = function({ x = 0, y = 0 }) {
  return this.attr("transform", function() {
    const x_pos = typeof x === "function" ? x.apply(this, arguments) : x;
    const y_pos = typeof y === "function" ? y.apply(this, arguments) : y;
    return `translate(${x_pos},${y_pos})`;
  });
};
```
