### ISSUE TITLE
selection append with use cannot render right

### ISSUE THREAD

**Issue by liuyepiaoxiang** [d3/d3-selection#251]
1.  What have Idone?
I try to use d3.selection link this, to get a item by data
```
d3.selectAll("g").append((d) => {
 if(d.type === 'use) {
 return document.createElement("use");
} else {
return document.createElement("rect")
}
).attr('xlink:href', '#arrow');
```

2. What have I got?
I got `<use xlink:href="#arrow"></use>`,but cannot get the defer item.

3. What was expected?
After render, use can get the defer that the id pointing to.

**Comment by Fil** [comment]
It seems to be working here https://github.com/d3/d3-selection/issues/251

If you have a question about D3’s behavior and want to discuss it with other users, please consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤖

**Comment by mbostock** [comment]
You need to use document.createElementNS (see also d3.create and d3.creator) to create SVG elements in their appropriate namespace; you can’t use document.createElement.

Also @Fil were you trying to link to a different issue? #251 is this issue.
