### ISSUE TITLE
Datum object inherit by reference but update by replacement

### ISSUE THREAD

**Issue by ChrisHSandN** [d3/d3-selection#254]
I don’t know whether this is a bug, an unavoidable gotcha, or me just using it wrong (but it has caught me out a few times)...

1. Bind JavaScript object as the datum for a parent node
2. Append child node to this parent node 
3. Automatically `child.datum()` === `parent.datum()` (e.g. child datum is a **reference** to the parent node datum object)
4. Update the parent nodes datum object
5. Child nodes datum is the same object so changes as well
6. Call `data()` again on the parent
7. `child.datum()` !== `parent.datum()` anymore so child has ‘old data’ so to speak

It feels like there is an inconsistency here as the data structure of the diagram is changing once `data()` is called the 2nd time:

Maybe either:
- `parent.datum()` should !== `child.datum()` (so objects are copied so there are no references)

Or:
- When a datum is an object it should not be replaced but its properties updated to match the new incoming object.

```js
const svg = d3.select('svg');

// add a parent <g>
const g = svg
  .selectAll('g')
  .data([{
    fill: 'red',
  }])
  .enter()
  .append('g');
  
// add a circle to the <g>
g
  .append('circle')
  .attr('r', 100)
  .style('fill', d => d.fill);
  
// directly update the datum on the <g>
svg
  .selectAll('g')
  .each(d => d.fill = 'green');
  
// <circle> datum updates as well (due to it being a reference rather than a copy)
svg
  .selectAll('circle')
  .style('fill', d => d.fill);
  
// bind new data to the <g>
svg
  .selectAll('g')
  .data([{
    fill: 'blue',
  }]);
  
// now the <circle> datum reference is broken and the circle has the previoud datum value (green rather than blue)
svg
  .selectAll('circle')
  .style('fill', d => d.fill);
```
(d3 v5.16.0)

p.s. This is not a question asking how to workaround this, I understand the new datum can be copied from parent to child again through the use of a `select()` or a `selectAll().data(d => [d])`.

**Comment by Fil** [comment]
As documented, when using *selection.*append, “Each new element inherits the data of the current elements”; but there's no consistency (and no promise of consistency) beyond that.

If your robot puts all the red socks in the red drawer, then puts a blue label on the red drawer, you end up with red socks in the blue drawer :)
