### ISSUE TITLE
Why was the node index argument removed from the event listener in version 6?

### ISSUE THREAD

**Issue by alancleary** [d3/d3-selection#259]
The [D3 6.0 migration guide](https://observablehq.com/@d3/d3v6-migration-guide) describes changes to event management in D3 version 6. This includes no longer passing the selection index of the target node (or the elements in the selection) as an argument to the listener. I see you can still access the index from the selection or by adding it to the datum, but these techniques are both awkward and inconsistent with other selection functions, e.g. attr.

I think just adding the event as a listener argument (thanks for doing that BTW!) and leaving the other arguments would've been great, but that's just my opinion. Long story short, I'm just wondering what the motivation for this change was. Cheers!

**Comment by mbostock** [comment]
To keep things simple and to avoid a memory leak. Unlike data which is bound to elements (*element*.__data__), the index is an ephemeral property of the selection and requires a closure to remember, meaning that previously whenever you called *selection*.on it had to retain a reference to that *selection* forever.
