### ISSUE TITLE
selection.join() enter and update duplication

### ISSUE THREAD

**Issue by xy2iii** [d3/d3-selection#260]
In [What Makes Software Good](https://medium.com/@mbostock/what-makes-software-good-943557f8a488#708a), it's mentionned that doing things both on enter and update introduces duplication, like in this code:

```js
var text = g
  .selectAll("text")
  .data(data, key); // JOIN

text.exit() // EXIT
  .remove();

text // UPDATE
  .attr("x", function(d, i) { return i * 32; });
  
text.enter() // ENTER
  .append("text")
    .attr("x", function(d, i) { return i * 32; }) // 🌶
    .text(function(d) { return d; });
```

In D3 v4, there's the [_selection_.merge()](https://github.com/d3/d3-selection#selection_merge) API which works around this problem by merging both enter and update:
```js
var text = g
  .selectAll("text")
  .data(data, key); // JOIN

text.exit() // EXIT
  .remove();

text.enter() // ENTER
  .append("text")
    .text(function(d) { return d; })
  .merge(text) // ENTER + UPDATE
    .attr("x", function(d, i) { return i * 32; });
```

But, with the [_selection_.join()](https://github.com/d3/d3-selection#selection_join) API, it seems the same problem is present again:

```js
var text = g
  .selectAll("text")
  .data(data, key)
  .join(
    enter => enter.append("text")
      .attr("x", (d, i) => i * 32)
      .text(d => d),
    update => update
      .attr("x", (d, i) => i * 32), // 🌶
    exit => exit.remove()
  )
```

Is there a way to do this with `join()` without the duplication?

**Comment by Fil** [comment]
~~~js
var text = g
  .selectAll("text")
  .data(data, key)
  .join(
    enter => enter.append("text")
      .text(d => d),
    update => update, // 🌶
    exit => exit.remove()
  ).attr("x", (d, i) => i * 32)

~~~

or simply

~~~js
var text = g
  .selectAll("text")
  .data(data, key)
  .join("text").text(d => d).attr("x", (d, i) => i * 32)
~~~

see https://observablehq.com/@d3/selection-join
> selection.join appends entering elements and removes exiting elements to match the data! Entering and updating elements are merged (and ordered), allowing chained operations on the result.
