### ISSUE TITLE
selection.join() improvements

### ISSUE THREAD

**Issue by pavelschon** [d3/d3-selection#264]
First of all, I'd like to thank for the `selection.join()`, it's a great improvement over traditional enter-update-exit pattern.
However, I feel there's some space for improvements.

Using arrow functions are good only for the simple case like this:
```javascript
selection.join(
    enter => enter.append('div').classed('enter', true),
    update => update.classed('enter', false).classed('update', true),
    exit => exit.classed('update', false).classed('exit', true).transition().remove()
)
```
When  you need to do something more complex, you will probably have to use regular functions:

```javascript
selection.join(
    function(enter) {

    },
    function(update) {

    },
    function(exit) {
    
    }
)
```
or even factor-out functions for readability:
```javascript
function doEnter(enter) {
   
}

function doUpdate(update) {

}

function doExit(exit) {
    
}

selection.join(doEnter, doUpdate, doExit)
```
    
One may not need doUpdate() and will write:
```javascript
selection.join(doEnter, doExit)  // bug!
```

I propose the following syntax: pass functions in the object:

```javascript
selection.join({
    enter: doEnter,
    update: doUpdate,
    exit: doExit
})
```
Passing functions in the object will prevent bugs and improve the readability.

**Comment by mbostock** [comment]
Thanks for the feedback, but I don’t want to change the API.

**Comment by pavelschon** [comment]
So you're happy with the current API? Could you elaborate more?

**Comment by curran** [comment]
@pavelschon The motivations for the proposal are not clear.

>When you need to do something more complex, you will probably have to use regular functions:

Why? The only reason to change would be if you need to access `this`.

>Passing functions in the object will prevent bugs and improve the readability.

How so? What is the benefit?

Also keep in mind that changing this API would be a breaking change, and keeping the old API as well would introduce more surface area to the library. This proposal does not seem to hold water IMO.

**Comment by pavelschon** [comment]
_How so? What is the benefit?_

It's already mentioned in the first post - if you pass doExit as 2nd positional argument, it will most likely cause a bug:
```
selection.join(doEnter, doExit)  // bug!
```
SInce JS does not support named arguments, then the only way to do it is to pass an object.

**Comment by pavelschon** [comment]
And it is not a breaking change: you can call join() in 2 ways already:
```
selection.join(element) // as a shorthand
selection.join(doEnter, doUpdate, doExit)
```
What's the problem to add another API like:
```
selection.join(obj)
```
?
