### ISSUE TITLE
Using const in size.js breaks IE11

### ISSUE THREAD

**Issue by boyanio** [d3/d3-selection#272]
Code in D3 is written in a way to support older browsers and since we have clients on IE11, size.js throws an error there for them, because of const.

**Comment by gordonwoodhull** [comment]
Please see the release notes - this is intentional.

https://github.com/d3/d3-selection/releases/tag/v2.0.0

You must stick with 1.x or transpile if you still need to support IE.

**Comment by boyanio** [comment]
Yes, just realized that and saw there were other breaking changes for the older browser. Thanks for this!
