### ISSUE TITLE
Selection.one

### ISSUE THREAD

**Issue by curran** [d3/d3-selection#294]
Managing a single element is a common scenario. For example, a group element that contains an axis or legend. It might be a nice idea to consider introducing a utility that makes it simpler to manage a single element.

The most common pattern I find myself using is something like this:

```js
const xAxisG = g.selectAll('.x-axis').data([null]).join('g').attr('class, 'x-axis');
```

Something similar can be seen [in d3-axis for managing the domain path](https://github.com/d3/d3-axis/blob/main/src/axis.js#L52).

Wouldn't it be nicer to have a utility that does this:

```js
const xAxisG = d3.one(g, 'g', 'x-axis');
```

?

Here's a strawman implementation:

```js
const one = (selection, tagName, className) =>
  selection.selectAll('.' + className).data([null]).join(tagName).attr('class', className)
```

**Comment by curran** [comment]
An iteration:

 * Moves `tagName` to be the last argument and defaults it to `'g'`, which is the most common use case.
 * Renames `tagName` to `name` for consistency with other methods such as `selection.create`.

```js
    // Manages a single element.
    const one = (selection, className, name = 'g') =>
      selection
        .selectAll(name + '.' + className)
        .data([null])
        .join(name)
        .attr('class', className);
```

Example snippet before:

```js
      svg
        .selectAll('.y-axis')
        .data([null])
        .join('g')
        .attr('class', 'y-axis')
        .attr('transform', `translate(${margin.left}, 0)`)
        .call(axisLeft(yScale));
```

After:

```js
      one(svg, 'y-axis')
        .attr('transform', `translate(${margin.left}, 0)`)
        .call(axisLeft(yScale));
```

**Comment by curran** [comment]
It could even parse the tag name and class from a selector string:

```js
const one = (selection, selector) => {
  const [name, className] = selector.split('.');
  return selection
    .selectAll(name + '.' + className)
    .data([null])
    .join(name)
    .attr('class', className);
}
```

I like this because when you read its invocation, the tag name is clear, and there is no "magic" (no default "g" value).
```js
one(svg, 'g.y-axis')
  .attr('transform', `translate(${margin.left}, 0)`)
  .call(axisLeft(yScale));
```

**Comment by curran** [comment]
Would be super useful right now.

I have this in some code currently:

```js
svg.append("g").call(xAxis);
```

and I need to change it to this:

```js
svg
  .selectAll('.x-axis')
  .data([null])
  .join('g')
  .attr('class', 'x-axis')
  .call(xAxis)
```

but I wish I could change it to this instead:

```js
one(svg, 'g.x-axis').call(xAxis);
```

Would be super nice!

**Comment by curran** [comment]
Another use case - setting up the SVG container:

Before:
```js
const svg = select('body')
  .selectAll('.viz')
  .data([null])
  .join('svg')
  .attr('class', 'viz')
  .attr('width', width)
  .attr('height', height);
```

After:

```js
const svg = one(select('body'), 'svg.viz')
  .attr('width', width)
  .attr('height', height);
```

**Comment by curran** [comment]
Closing as the change is not welcome https://github.com/d3/d3-selection/pull/300#issuecomment-1060800370

**Comment by curran** [comment]
Actually, wait a minute - we can avoid a string-based DSL and still implement the module.

Based on this feedback:

>I don’t want to introduce (and design and maintain) a new string-based DSL.

the proposal can be modified back to its original form:

```js
one(g, 'g', 'x-axis');
```

**Comment by curran** [comment]
The class name argument could be optional. For example:

```js
one(svg, 'g');
```

Example from https://github.com/d3/d3-selection/issues/301

**Comment by curran** [comment]
Latest implementation for reference:

```js
const one = (selection, name, className) =>
  selection
    .selectAll(name + '.' + className)
    .data([null])
    .join(name)
    .attr('class', className);
```

I find myself copying this into codebases often, so thought I'd post it here for easy reference.

**Comment by curran** [comment]
An interesting alternative solution https://the-politico.github.io/nicar2019_reactive-d3/parts/idempotence/

**Comment by Fil** [comment]
see discussion on #300

**Comment by curran** [comment]
Added to https://github.com/curran/d3-rosetta
