### ISSUE TITLE
Is anyone working on D3.ts ?

### ISSUE THREAD

**Issue by nwheatleKite** [d3/d3-selection#302]
Hello,

I'm considering re-writing d3-selection in typescript. Is anyone already doing this? I understand that many other modules would need to be converted to eventually step over, but this is the best place to start. 

I don't want to start if others are already in the middle of it.

**Comment by mbostock** [comment]
You can find externally maintained types for d3-selection here:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3-selection

I’m not currently planning on porting D3 to TypeScript, but I have been using TypeScript in other projects, so I may get around to it eventually.
