### ISSUE TITLE
`pointer.js`  function is not available for import through `d3-selection`

### ISSUE THREAD

**Issue by nick-kl4us** [d3/d3-selection#310]
I see the [function file in the repo](https://github.com/d3/d3-selection/blob/main/src/pointer.js), but I am not able to import it.

`import {pointer} from 'd3-selection'`

Also, this function seems to be using a deprecated method [createSVGPoint](https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint).

Any thoughts on revamping this file to use more current methods along with properly exporting it?

If I'm missing something here and there is a way to import this function, please correct me.

**Comment by Fil** [comment]
what version of d3-selection are you trying to import from? pointer was added in version 2.

**Comment by mbostock** [comment]
Assume this is referring to an older version, since the export is here:

https://github.com/d3/d3-selection/blob/91245ee124ec4dd491e498ecbdc9679d75332b49/src/index.js#L7

**Comment by nick-kl4us** [comment]
I'm on v3, the latest you have on npm.

**Comment by nick-kl4us** [comment]
@mbostock have you tried reproducing before closing?
Do I need to create a plunkr for you to give this attention? @Fil

**Comment by nick-kl4us** [comment]
I also didn't get a response to the fact that you're using a deprecated method?

**Comment by Fil** [comment]
> have you tried reproducing

I have tried and it worked for me.

**Comment by nick-kl4us** [comment]
@Fil how are you importing? what syntax?

**Comment by Fil** [comment]
Exactly the same as your question. Maybe you're doing it in a different environment in which it doesn't work.

To be complete:

```bash
❯ cat index.mjs
import {pointer} from 'd3-selection'
console.warn(pointer);

❯ cat package.json
{
  "dependencies": {"d3-selection": "3"}
}

❯ yarn
yarn install v1.22.19
…
✨  Done in 0.03s.

❯ node index.mjs
[Function: default]

```
