### ISSUE TITLE
Cannot import {pointer} function as it is not available to import

### ISSUE THREAD

**Issue by husseinhaidarsword** [d3/d3-selection#317]
I'm trying to upgrade my d3 package from 5==>7. For that, I am following the migration guide one major version at a time.
As per this: https://observablehq.com/@d3/d3v6-migration-guide, it mentions that mouse functions are deprecated at and replaced with the pointer function.

I have tried d3.pointer and pointer - nothing works

When trying to use it after upgrading to v6 for d3 and v3.0.0 for d3-selection, I am unable to import the pointer function, although when digging inside the dist - the library clearly exports it.
package.json:L
    "@ngx-translate/http-loader": "^7.0.0",
    "d3": "^6.0.0",
    "d3-geo": "^1.11.3",
    "d3-selection": "^3.0.0",
    "file-saver": "^2.0.5",
    "geojson": "^0.5.0",

    "@cypress/schematic": "^2.5.1",
    "@ngrx/schematics": "^14.3.2",
    "@types/d3": "^5.7.0",
    "@types/d3-geo": "^1.11.3",
    "@types/file-saver": "^2.0.5",

**Comment by Fil** [comment]
Please share details of how you're importing, because it definitely should work.

**Comment by husseinhaidarsword** [comment]
@Fil  
![image](https://github.com/d3/d3-selection/assets/162560420/6677f69a-ef4e-428a-912b-d0360d796884)
I've tried several libraries

**Comment by Fil** [comment]
I can't reproduce: I did the following:

npm init
npm add d3
code index.js

![import pointer](https://github.com/d3/d3-selection/assets/7001/2b41b434-232a-4601-8325-0609cdf34e00)

**Comment by mbostock** [comment]
Looks like you still have old types installed (@types/d3), so you’ll need to upgrade those too. Also, you shouldn’t import d3 and d3-selection — either use d3 if you want everything bundled together, or use the individual libraries.
