### ISSUE TITLE
Open questions.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#47]
Do we want a full hierarchy, or should we limit selections to a single level of nesting (groups + nodes) as in 3.x? The primary benefit of the full hierarchy is that it allows us to track all parent data and indexes to functions {d, i, p, j, …}. These can either be passed to selection functions or exposed as globals during function invocation.

How useful is it to have access to the parent data and index? The parent index alone provides a way to access the parent data, albeit awkwardly. Not exposing parent data encourages parent data to be pushed down to children, which (while perhaps a pain) has a potential benefit in that nodes can be reselected with their data already bound, rather than needing to reselect the parent and then the child to restore the full context.

I seem to recall some cases where having access to the parent data simplified the creation of small multiples or a scatterplot matrix. http://bl.ocks.org/mbostock/4063663

Do we want to pass all parent data and indexes to functions? Or would it be better to use fixed arguments, say {d, i}? In the latter case, is there a third argument equivalent to {d, i, array} in *array*.forEach? Would the last argument be the array of data for group (which is awkward because that array isn’t typically materialized)? Or would it be the array of elements? Or would it be the parent node’s data?

…

**Comment by mbostock** [comment]
I think it’s time to implement more examples of small multiples, scatterplot matrices, trellis charts, facets, etc. to determine reasonable use cases for parent data and indices.

**Comment by mbostock** [comment]
I think {*d*, *i*, *nodes*} could be a good choice, where *nodes* is the current group. For example, that makes it easier to select the last node in a selection (*i* === *nodes*.length - 1)

**Comment by curran** [comment]
With {*d, i, nodes*}, how could one access *j*? It seems to me that for implementing small multiples, the *j* in {*d, i, j*} is extremely useful. Here are some examples I have made of small multiples using *j*:

[![](http://bl.ocks.org/curran/raw/d0a42741ce0cf6cdc3ab/thumbnail.png)](http://bl.ocks.org/curran/d0a42741ce0cf6cdc3ab) [![](http://bl.ocks.org/curran/raw/e025a50dbaae7186e516/thumbnail.png)](http://bl.ocks.org/curran/e025a50dbaae7186e516) [![](http://bl.ocks.org/curran/raw/11b02f8917fac66d6fe5/thumbnail.png)](http://bl.ocks.org/curran/11b02f8917fac66d6fe5) [![](http://bl.ocks.org/curran/raw/40d5e61963abf20da067/thumbnail.png)](http://bl.ocks.org/curran/40d5e61963abf20da067)

Conceivably, these small multiples could facet across both X and Y, which would make the *k* in the proposed {*d, i, j, k, ...*} args idea useful.

Some ideas for small multiples examples - I could imagine faceting these examples in both X and Y to see what the code might look like:

[![](http://bl.ocks.org/curran/raw/805413fb3b2efaada1ce/thumbnail.png)](http://bl.ocks.org/curran/805413fb3b2efaada1ce) [![](http://bl.ocks.org/curran/raw/d4e2b2854f25429a06aa/thumbnail.png)](http://bl.ocks.org/curran/d4e2b2854f25429a06aa) [![](http://bl.ocks.org/curran/raw/9eea6a43904b1a158e92/thumbnail.png)](http://bl.ocks.org/curran/9eea6a43904b1a158e92) [![](http://bl.ocks.org/curran/raw/b1014a71757ce72444e1/thumbnail.png)](http://bl.ocks.org/curran/b1014a71757ce72444e1)

I feel like the {*d, i, j, k, ...*} approach would be nice. Or, maybe {*d, i, nodes*} would be nicer, but I'm just not seeing how to derive what would be *j, k, ...* from *nodes* here. One wild guess is that it could look something like this (I'm not sure if/how the index is tracked in the data structure):

```javascript
var j = nodes._parent._index;
var k = nodes._parent._parent._index;
var l = nodes._parent._parent._parent._index;
```

**Comment by mbostock** [comment]
The idea is you wouldn’t need to access the other indexes, but I haven’t experimented with it yet, so I can’t say exactly how it would work. :)

**Comment by mbostock** [comment]
I have pushed a mostly-untested implementation to the [bilevel branch](https://github.com/d3/d3-selection/tree/bilevel). I plan on writing tests and experimenting to see how well this new approach works. The implementation is certainly simpler!

**Comment by mbostock** [comment]
I’ve merged the new bilevel selection implementation into master and also simplified how parents are tracked by using a parallel parents array.

A nice property of this new approach is that *selection*.data can evaluate the values function in exactly the same manner as other selection functions: the values function gets passed {*d*, *i*, *nodes*} where *this* is the parent node, *d* is the parent datum, *i* is the parent (group) index, and *nodes* is the array of parent nodes (one per group).

Although this change restricts functionality, in the sense that you cannot access the parent node from within a selection function (nor the parent data, nor the group index), I believe this is ultimately A Good Thing because it should encourage simpler code. A downside of relying on parent data is that you can’t easily re-select an element to restore its context, for example to recompute an attribute: you must re-select the ancestors and then re-select the descendants.

Also, there are already two ways to access parent data. You can push that parent data down into the child data, replicating it for each child. Or you can use [*selection*.each](https://github.com/d3/d3-selection#selection_each) to create a context (a closure) that makes parent and child data accessible simultaneously. This is functionally similar to exposing the parent data to every selection methods, but now you have to explicitly opt-in to this via *selection*.each. Hopefully this encourages people to favor simpler, flat structures when possible.

Here’s my take on sized donut multiples using this approach:

[![screen shot 2016-01-20 at 4 30 46 pm](https://cloud.githubusercontent.com/assets/230541/12467780/2e4189cc-bf93-11e5-803f-4d8706c80620.png)](http://bl.ocks.org/mbostock/4c5fad723c87d2fd8273)

Note that only the arcs need to be drawn within the *selection*.each context, because only they depend on the parent data to compute the arc radius. The labels do not depend on the parent context, so I’ve moved them outside the each. You could put them inside, of course, but I think it’s probably best to minimize what’s done inside the each to favor flatness.

**Comment by curran** [comment]
Awesome. Thank you for this example, I didn't realize that *selection*.each could be used in that way.

**Comment by WardCunningham** [comment]
I have struggled with this problem but did not recognize it until your post today. (I solved my problem pushing data down.)

I suspect this will become an important idiom of d3 programming. Is "bilevel selection" the best name? It didn't work for me but it might for others when explained as part of selection.

**Comment by mbostock** [comment]
[“Nested selection”](http://bost.ocks.org/mike/nest/) is what I normally use. (See also [How Selections Work](http://bost.ocks.org/mike/selection/).) I used “bilevel” here to distinguish them from the earlier alpha implementation of arbitrarily-hierarchical selections, where the selections were trees of arbitrary depth rather than limited to one level of grouping.

**Comment by curran** [comment]
Ended up at this issue again after so much water under the bridge!

Here's a snippet I crafter after re-remembering this usage of `.each` for nesting, I thought it may be useful to others who end up here:

```js
const nested = nest().key(layerValue).entries(data);
        
let layerGroups = g.selectAll('g.layer').data(nested);
layerGroups = layerGroups.enter().append('g').attr('class', 'layer')
  .merge(layerGroups);
          
layerGroups.each(function(layerEntry, j) {
  const { key, values } = layerEntry;     
  const circles = select(this)
    .selectAll('circle').data(d => d.values);
  circles.enter().append('circle')
    .merge(circles)
      .attr('cx', d => xScale(xValue(d)))
      .attr('cy', d => yScale(yValue(d)))
      .attr('r', d => radiusScale(radiusValue(d)))
      .attr('fill', j === 0 ? 'white' : 'black'); // <---- This is the place where the parent index is used.
});
```
