### ISSUE TITLE
Publish current version with fixed selection/classed

### ISSUE THREAD

**Issue by jimkang** [d3/d3-selection#56]
The current 0.6.0 package published to NPM has a version of the `selection/classed.js` module that uses `setConstant`. This doesn't work because it looks like it's since been renamed to `classedConstant`. In master, it uses `classedConstant` instead, and thus, is fine. Can you publish this fix to NPM?

**Comment by mbostock** [comment]
Yes, soon.

**Comment by mbostock** [comment]
Released 0.6.1.

**Comment by jimkang** [comment]
Thanks!
