### ISSUE TITLE
selection.merge(selection)?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#60]
What if *enter*.append didn’t copy the created nodes into the update selection, and if instead you could explicitly merge the entered nodes into the update selection, creating a new selection. Something like this:

```js
var childUpdate = parent.selectAll("child").data(data),
    childExit = childUpdate.exit().remove(),
    childEnter = childUpdate.enter().append("child"),
    child = childUpdate.merge(childEnter); // enter + update
```

Could we make selections immutable if we did this? Edit: YES.

~~Is *source*.merge(*destination*) or *destination*.merge(*source*) more natural?~~ Edit: IRRELEVANT. They are equivalent if it returns a copy!

The method should probably check that the selections have the same structure (same parents, same group sizes).

**Comment by mbostock** [comment]
I really like that this removes the `_update` back link, removes the special magic from selection.append for populating update from enter, and makes selection.enter and selection.exit no longer destructive. It also makes explicit when enter is merged into update, which should make many usages clearer.

Plus, immutability!

**Comment by curran** [comment]
Wow, that code looks super clean and nice. It's nice to have this kind of fine grained control, and making selections immutable is a huge win IMO. I like this solution.

**Comment by mbostock** [comment]
Thanks, @curran.

**Comment by mbostock** [comment]
Leads to some interesting patterns:

```js
var p = d3.select("body").selectAll("p");

p = p.data([1, 3]);
p.exit().remove();
p = p.enter().append("p").text(function(d) { return d; }).merge(p);

p = p.data([0, 1, 2, 3, 4]);
p.exit().remove();
p = p.enter().append("p").text(function(d) { return d; }).merge(p);
```

Hmm.

**Comment by mbostock** [comment]
I wonder if *selection*.merge(*selection*) is too generic, if the only use case it’s intended to support is combining the enter and update selections. For instance, maybe *enter*.update() is equivalent to *enter*.merge(*update*), and has the advantage that you don’t need another reference to the update selection?

On the other hand, maybe *selection*.merge(*selection*) could be used to combine filtered selections, too? Currently *selection*.filter doesn’t preserve the index, but maybe it could.

**Comment by mbostock** [comment]
Thanks for the feedback, @WardCunningham.

I’m implementing d3-axis transitions now, which is a good test case for these changes. (Related d3/d3-transition#33.)

I think it might be difficult to support *enter*.update() since when we refer to the “enter” selection we either mean *selection*.enter(), which contains the placeholder nodes, or *selection*.enter().append(*name*), which contains the *materialized* entering nodes. To support *selection*.update() on the latter, you’d have to propagate the reference back to the update selection twice, first to the enter selection and then to the materialized enter selection. Of course that’s doable, but it’s a little awkward since you probably don’t want to propagate the reference to the update selection on every *selection*.append. 

Anyway. I think explicit references might be appropriate for now, even if slightly less convenient.
