### ISSUE TITLE
Select all child elements using selectAll() with no arguments

### ISSUE THREAD

**Issue by mindrones** [d3/d3-selection#63]
I'd like to select all child elements using `sel.selectAll()` with no arguments, instead of having to use `sel.selectAll('*')`, because it's more concise and expressive: it just reads "select all", perfect to me.

What do you think?

**Comment by mbostock** [comment]
I’m in favor of parsimony and explicitness, and I think `selection.selectAll("*")` is both clear and easy to type if that’s the behavior you want. Making that the default behavior when there is no argument would make the behavior less obvious to someone reading the code.

**Comment by mindrones** [comment]
OK, thanks!

**Comment by adumesny** [comment]
would have to agree with @mindrones . I expected `selectAll()` to just work (I was doing `selectAll('g')` but now need to support different children), and instead had to find this solution.

**Comment by mbostock** [comment]
I’d support *selection*.selectAll() throwing an error, though I’d want to use *arguments*.length to check because *selection*.selectAll(undefined) should be equivalent to *selection*.selectAll("undefined").

**Comment by adumesny** [comment]
while I have your attention :) seems like selecting all your immediate children ought to be dead simple... this is what I had to use, and complains in Typescript even with latest @types/selection
```ts
this.container.selectAll(function() {return this.childNodes; } as any)
```
(where container is selection of my svg root). 
Would have been nice to have a `selectChildren()` or such shortcut for what might be very common - see https://stackoverflow.com/questions/20569670/d3-selector-for-immediate-children

**Comment by mbostock** [comment]
Yeah, I could see *selection*.selectChildren (and *selection*.selectChild?) as being useful, and I could imagine the *selector* being optional there. I’d use *element*.children instead of *element*.childNodes, however, since you wouldn’t want to select text nodes.

**Comment by adumesny** [comment]
should I file a separate request to have `selection.selectChildren` ?
