### ISSUE TITLE
Documentation of 'group' argument in callbacks passed to each

### ISSUE THREAD

**Issue by tomwanzek** [d3/d3-selection#77]
@mbostock, first of all, thanks for the tremendous work on D3.

I started going through your v4 modules with an eye on updated typescript definition files to go along with them (current DefinitelyTyped definitions are for D3 3.x).

As I went through the code of the d3-selection module, I noticed that, the `each(...)` method and by implication the exposed methods which internally use `each` (e.g. `attr(...)`, `style(...)`, `prop(...)`) are all passed the `group` argument.

Before making any assumptions, is there a particular intent, why the 'group' argument is not described in the documentation, as is the passing in of the `datum` and `index` arguments?

As your library is a fast moving target, thanks to your prolific efforts :smile:, I am currently deciding on the best approach for getting the in-progress updated definitions to the community to co-evolve (pull request on DefinitelyTyped or similar).

I kept it in a local repo for the past few days, as I am also experimenting with a new typescript@next feature, which allows the typing of the 'this' context within functions such as the ones used as value functions passed into `each(...)` et al. with a DOM element binding.

Thanks in advance.

**Comment by mbostock** [comment]
> why the 'group' argument is not described in the documentation

No real reason, other than there was some hemming and hawing over what the right call pattern was, and I never went back and updated the documentation after making the decision on the final API to mimic the behavior of standard array methods such as *array*.forEach (see #47, d3/d3-array#17). I should update the documentation accordingly.
