### ISSUE TITLE
D3v4: Removed support for selection.attr(Object)?

### ISSUE THREAD

**Issue by arjenvanoostrum** [d3/d3-selection#78]
The current alpha release of D3v4 (4.0.0-alpha.49) does not support the syntax to pass an object to selection.attr(), where the current D3v3 release does:
> selection.attr(name[, value])
> name can also be an Object of name and value attributes.

Since I use this syntax often when many key-value pairs should be added to an element, I am wondering if this functionality will return in a future release?

**Comment by curran** [comment]
This functionality has been implemented in https://github.com/d3/d3-selection-multi

**Comment by mbostock** [comment]
Curran is correct; it was extracted to d3-selection-multi, which is not part of the default bundle.

**Comment by mbostock** [comment]
Also see the [d3-selection CHANGES](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection).

**Comment by arjenvanoostrum** [comment]
Thanks Curran and Mike, 
Must have overlooked this and was indeed using the default bundle. Well, that surely ends my internal debate on using the default bundle or compose my own!

**Comment by mbostock** [comment]
You can also load it on top of the default bundle, e.g.,

```html
<script src="https://d3js.org/d3.v4.0.0-alpha.49.min.js"></script>
<script src="https://d3js.org/d3-selection-multi.v0.3.min.js"></script>
```

**Comment by arjenvanoostrum** [comment]
Yes, however I was already thinking about it as I want to make the Dutch locale the default locale for  projects. I find myself copying the locale definition for each project involving (axis)labels. And that is, well, almost all the time. 

And now with v4.0 it's not that much effort to create a bundle with the d3-goodies I need.

Thanks again Mike for all the effort in both the codebase and documentation/examples. Great job.
