### ISSUE TITLE
Function selection_style doesn't work

### ISSUE THREAD

**Issue by klaujesi** [d3/d3-selection#82]
On D3 v3 you could write:

    .style({
       fill:"none",
       stroke:"#f00",
       "stroke-width":"10"
    })

but on V4, if you do that get nothing. Looking at the function selection_style inside style.js

```
function selection_style(name, value, priority) {
    var node;
    return arguments.length > 1                     // *
        ? this.each((value == null
              ? styleRemove : typeof value === "function"
              ? styleFunction
              : styleConstant)(name, value, priority == null ? "" : priority))
        : window(node = this.node())
            .getComputedStyle(node, null)
            .getPropertyValue(name);
  }
```

* here, argument.length = 1 because it recibe an object:
![screen](https://cloud.githubusercontent.com/assets/6095955/16901643/065be672-4c20-11e6-87b9-8704b7deecd9.png)

and `arguments.length > 1` fails on recognize the 3 arguments.

**Object.keys(arguments[0]).length** give the right styles counts.

For me this is a bug, not a feature :)

**Comment by mbostock** [comment]
See the release notes; you’ll need [d3-selection-multi](https://github.com/d3/d3-selection-multi).

**Comment by klaujesi** [comment]
Thanks Mike, now its works. 
Q: If you expect just one pair [key, value],  why do you use 'this.each'?

**Comment by mbostock** [comment]
Not sure I understand the question. When you call selection.attr (or other
selection methods) they typically apply to all elements in the selection,
so selection.each is used to implement iterating over the selected elements.

**Comment by klaujesi** [comment]
Sorry, you right. I misunderstand the code. Thanks a lot
