### ISSUE TITLE
What if selection.enter created detached nodes?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#84]
Currently _selection_.enter returns “placeholder” nodes, while _selection_.append creates nodes and then adds them to the DOM. But you could imagine a different way of doing things:

``` js
d3.selectAll("div")
  .data(data)
  .enter("div") // creates detached DIVs
    .attr("class", "foo")
    .append(); // appends detached DIVs to the DOM
```

The nice thing is that it makes _selection_.append and _selection_.remove more symmetric: both would return the current selection, after either appending the selected elements to, or removing the selected elements from, the DOM.

Of course, there’s still the case where you want to create and append elements without using a data-join. So we could introduce a _selection_.create method…

``` js
d3.select("body")
  .create("div") // creates a detached DIV
    .attr("class", "foo")
    .append();
```

And we could still have _selection_.append(_name_) as a convenience method, equivalent to:

``` js
selection.create(name).append();
```

The nice thing about this is that it eliminates the need for placeholder nodes, and encourages modifying DOM elements while they are detached (which is probably slightly faster). You’d still need some magic to have _enter_.append preserve the order relative to update, though.

**Comment by aubergene** [comment]
I like this, the symmetry with _selection_.remove feels right. Could you remove the second selector?

```js
d3.selectAll("div")
  .data(data)
  .enter() // creates detached DIVs, implied by selectAll
    .attr("class", "foo")
    .append(); // appends detached DIVs to the DOM
```

Could it work something like this for non-data join select? Where an empty selection is automatically an enter?
```js
d3.select('body').select('ul').create().attr('class', 'my-list').append();
d3.select('body').select('ul').create().attr('class', 'my-list').append();
// Can I have just one ul please :)
```

**Comment by mbostock** [comment]
Thanks for the feedback. I’m opposed to removing the second selector for the same reason that (by default) *selection*.append does not support [d3-jetpack style initialization](https://github.com/gka/d3-jetpack#selectionappend--selectioninsert) of classes and the id attribute. I see the appeal of convenience but it feels too implicit.

**Comment by mbostock** [comment]
For the create-a-missing-child case, I think you’d still use a data-join:

```js
d3.select("body")
  .selectAll("ul")
  .data(function(d) { return [d]; })
  .enter("ul")
    .attr("class", "my-list")
    .append();
```

But, I suppose one thing you could do is that that the *enter* selection by default includes all null nodes in a selection, rather than being by default empty. Then you could eliminate the data-join above, and it would be essentially what you described:

```js
d3.select("body")
  .select("ul")
  .enter("ul")
    .attr("class", "my-list")
    .append();
```

The exit selection would always be empty, until you join with data. Interesting idea. I wonder if it’s more confusing.

**Comment by mbostock** [comment]
One reason not to do the suggestion in the previous comment is that this default enter selection would have different structure than its originating selection (since you’re implicitly doing the selectAll and then joining to the single-element data array). The parents of the enter selection are the originating selection.

**Comment by aubergene** [comment]
I think I actually prefer first version with the explicit data join, as it's consistent with how selectAll is used. It's a lot like the pattern from v3 d3.axis which switched me on to the idea of selectAppend in the first place.

It looks like there can be good [performance improvements](http://ejohn.org/apps/fragment/) from using [detached nodes](http://ejohn.org/blog/dom-documentfragments/), and I guess you could do some creative caching using it too.

On the other point, I agree it's very implicit, but it's always bothered me that a clumsy edit can edit up with a situation like this, and that it violates the DRY principle.

```js
d3.selectAll("div")
  .data(data)
  .enter("span") // oops!
    .append();
```

**Comment by mbostock** [comment]
Closing to inactivity.
