### ISSUE TITLE
Create attrs() and styles() to help setting multiple attributes/styles

### ISSUE THREAD

**Issue by zipengwu** [d3/d3-selection#87]
Hi, sometime it's very annoying to set multiple attributes on a selection, especially when we need to do the same with another selection:
```javascript
selectionA
    .attr("cx", "1")
    .attr("cy", "2")

selectionB
    .attr("cx", "1")
    .attr("cy", "2")
    .attr("r", (d) => d.value)
```
How about to have a attrs()/styles() helper methods help setting multi-values at the sametime ? :
```javascript
selectionA
    .attrs({
        cx : 1,
        cy : 2
     })

selectionB
    .attrs({
        cx : 1,
        cy : 2,
        r : (d) => d.value
    })
```
Even better, this will enable reusing and extending the settings:
```javascript
var attributes = { cx : 1, cy : 2 };
selectionA.attrs(attributes);

attributes.r = (d) => d.value;
selectionB.attrs(attributes);
```

**Comment by jimkang** [comment]
Hey, there's a module that does exactly this! https://github.com/d3/d3-selection-multi

**Comment by mbostock** [comment]
As described in the [release notes](https://github.com/d3/d3-selection/releases/v1.0.0), this functionality is available as [d3-selection-multi](https://github.com/d3/d3-selection-multi).

**Comment by zipengwu** [comment]
Oups, okay thanks
