### ISSUE TITLE
Generalize selection.merge? or selection.update?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#89]
The current _selection_.merge implementation is limited to combining selections that have the same structure, such as ENTER and UPDATE, where the only difference is that some of the elements in the selection may be null.

Would it be possible to generalize _selection_.merge so that you could union arbitrary filtered selections, too? What would the logic be? You can’t drop null nodes because they are needed to preserve the index when merging ENTER and UPDATE.

If you can’t generalize _selection_.merge, would it be better to make it’s role in combining ENTER, UPDATE and EXIT explicit, e.g., replacing it with _selection_.update or some such? Related #86.

**Comment by mbostock** [comment]
An example of the hypothetical *selection*.update:

```js
var child = parent.selectAll("child")
  .data(function(d) { return [d]; })
  .enter().append("child")
    .attr("class", "only-child")
  .update() // merges ENTER’d child with UPDATE
    .attr("name", function(d) { return d.name; });
```

**Comment by mbostock** [comment]
I also wonder if it’d be useful to have a convenience method for a variant of *selection*.selectAll, say *selection*.selectOne, that returns a one-or-zero group for each selected element, joined to the singleton data, so you could say:

```js
var child = parent.selectOne("child")
  .enter().append("child")
    .attr("class", "only-child")
  .update() // merges ENTER’d child with UPDATE
    .attr("name", function(d) { return d.name; });
```

But I fear that would exacerbate the existing confusion between *selection*.select and *selection*.selectAll. Maybe especially so with the name *selection*.selectOne, though not sure if *selection*.selectOptional or *selection*.selectMaybe would be better.

**Comment by timruffles** [comment]
I think taking either one of these roots is important - either make `.merge()` live up to what it sounds like it should do, or rename it. As it stands `.merge()` over-promises.

**Comment by aubergene** [comment]
I'm afraid I think all those names would just make it more confusing. I'm fairly happy with how merge works currently, or I haven't yet discovered problems 😄. 

I think there is some improving how selections work. Currently I see very few examples in the wild where the rendering can be repeatedly called without appending elements multiple times, and unfortunately often the _easiest_ solution is just to chuck away large chunks of the DOM and re-render, losing any chance of nice transitions in the process. 

I added some thoughts to #84 which I thought looks really interesting. I can see the problem of losing the enter selection with something like [selectAppend](https://github.com/1wheel/d3-jetpack-module/blob/master/src/selectAppend.js), although pragmatically most of the time I'm only adding an id or class, and it handles that.

**Comment by julians** [comment]
I was just looking for a way to combine two filtered selections and `selection.merge()` sounded like the natural way to do it. Only after some googling and very closely reading the documentation I figured this wasn’t the case. Out of curiosity: what _is_ the recommended way to merge two filtered selections?

**Comment by mbostock** [comment]
There are two difficulties with merging selections in the general case:

1. Selections are hierarchical: nodes are grouped by parent. See [Nested Selections](https://bost.ocks.org/mike/nest/) and [How Selections Work](https://bost.ocks.org/mike/selection/).

2. Selections can be sparse. Most often, this occurs as a result of calling [*selection*.select](https://github.com/d3/d3-selection/blob/master/README.md#selection_select), which returns a new selection with the same parents and indexes as the current selection.

Also, there’s the question of how you handle duplicate nodes (*i.e.*, nodes that are present in both selections to be merged): you probably don’t want duplicate nodes to appear twice in the merged selection.

The current implementation of *selection*.merge only handles the case where the two selections have the same structure (*i.e.*, the same parents and indexes), and returns a selection with the same structure. It doesn’t check for duplicate nodes because it assumes the two selections are simply sparse copies of the same selection.

A nice consequence of this design is that you can use *selection*.select instead of *selection*.filter to filter a selection, and then merge the filtered selections back together using *selection*.merge. For example:

```js
var selection = …,
    a = selection.select(function(d) { return d.type === "a"; }),
    b = selection.select(function(d) { return d.type === "b"; }),
    ab = a.merge(b);
```

If you don’t care about preserving structure or handling duplicates, you could use *array*.concat and d3.selectAll:

```js
var ab = d3.selectAll(a.nodes().concat(b.nodes()));
```

Or equivalently with d3.merge:

```js
var ab = d3.selectAll(d3.merge([a.nodes(), b.nodes()]));
```

**Comment by Herst** [comment]
@mbostock wrote:
> Or equivalently with d3.merge:
> ```js
> var ab = d3.selectAll(d3.merge([a.nodes(), b.nodes()]));
> ```

Since `.nodes()` and not `.node()` is used here this would result in an array of arrays to be given to `d3.selectAll` which I don't think is ever desired. Instead you would just need to concatenate theses arrays:
```js
var ab = d3.selectAll(d3.merge(a.nodes().concat(b.nodes())));
```

**Comment by nadavpa** [comment]
I noticed that `selection.merge`  is not symmetrical, meaning `a.merge(b) != b.merge(a)`
It happens when trying to merge an empty selection to a non empty selection.
This behavior is error-prone and can happen a lot when working with nested selections.
If I add a simple check in merge.js:
` if(this.empty() && !selection.empty()){
    return selection.merge(this);
  }
...
`
then the merge succeeds as expected.

**Comment by doganmeh** [comment]
> I noticed that `selection.merge` is not symmetrical, meaning `a.merge(b) != b.merge(a)`
> It happens when trying to merge an empty selection to a non empty selection.
> This behavior is error-prone and can happen a lot when working with nested selections.
> If I add a simple check in merge.js:
> `if(this.empty() && !selection.empty()){ return selection.merge(this); } ...`
> then the merge succeeds as expected.

I agree with that it is not symmetrical, and it is error prone. But not for the aforementioned reason. 

`a.merge(b)` takes each item in a and compares with the same index item in b, takes a[i] or b[i], anything in b that is beyond the length of a is ignored. This is well documented [here](https://github.com/d3/d3-selection#selection_merge), although there has been quite a bit conversation on how to generalize `merge` and this thread is one them. 

The error-proneness stems from that "merge" is usually understood as "union", and in fact it is referred to as "union" (see [item 7 here](https://github.com/d3/d3-selection#selection_data) for example) although the implementation is clearly not. Here is the [code](https://github.com/d3/d3-selection/blob/master/src/selection/merge.js)

**Comment by mbostock** [comment]
The new [*selection*.join](https://beta.observablehq.com/@d3/selection-join) method obviates the need to use *selection*.merge in nearly every case, so there’s not much of a need to change its behavior. If anything, we might wish to deprecate it.
