### ISSUE TITLE
README: selection.classed("foo", function() { return Math.random(); });

### ISSUE THREAD

**Issue by urbanhop** [d3/d3-selection#90]
From the docu of selection.classed(names[, value]) in README:

> For example, to randomly associate the class foo with on average half the selected elements: 

    selection.classed("foo", function() { return Math.random(); });

Is this correct? Math.random() never returns a truthy value? Maybe it should read

    selection.classed("foo", function() { return Math.random() > .5; });

**Comment by mbostock** [comment]
Yep, this was a mistake. Thanks!

Small point: Math.random() almost always returns a truthy value. The only falsey value it returns is 0, which is possible but extremely unlikely.

**Comment by urbanhop** [comment]
small but truthy!
;-)
