### ISSUE TITLE
Update selection different from V3

### ISSUE THREAD

**Issue by trevithj** [d3/d3-selection#92]
Several pieces of my existing d3 code make use of a separate updating function, to handle cases where the data gets frequently changed. Some of that code no longer seems to work when using d3-selection. It appears that the `d3.selectAll(..).data(..)` function returns something different in v4.

```
function doUpdate(updateSel) {
	console.log(updateSel);
	updateSel.text(function(d) { return d;});
}

var dat = ["One","Two","Buckle my shoe"];
var sel = d3.selectAll("p.test").data(dat);                  //the update selection, as was.
var upd = sel.enter().append("p").classed("test", true);     //the enter selection?
/* call doUpdate to initialize the selection */
//doUpdate(sel); //Worked fine in v3, doesn't work in v4.
//doUpdate(upd); //works OK in v3 and v4

...
/* call doUpdate to handle changes in the array */
dat[2] = "Test my code";
//doUpdate(sel.data(dat));	//OK in v3, not in v4.
//doUpdate(upd.data(dat));	//OK in both versions.
//doUpdate(sel);			//FYI - I expected this to work, given dat is the same array.
```

**Comment by mbostock** [comment]
Yes. Please read the [release notes for d3-selection 1.0](https://github.com/d3/d3-selection/releases/tag/v1.0.0) for details on what changed between v3 and v4.

**Comment by trevithj** [comment]
Thanks for prompt reply!
Hmm. Unclear on what the difference is between
````
var upd = sel.enter().append("p").classed("test", true);`
````
and
````
var upd = sel.enter().append("p").classed("test", true).merge(sel);
````
If I understand the usage correctly.
With reference to https://github.com/d3/d3-selection/issues/89 I would vote for something like:
````
sel.enter().append("p").classed("test", true);
var upd = sel.update();
````

**Comment by mbostock** [comment]
In v3, this is the materialized *enter* selection—it contains just the enter nodes you appended:

```js
var upd = sel.enter().append("p").classed("test", true);
```

So, it’s misleading to call it `upd` (assuming that’s short for *update*). In v3 the above code also had the side-effect of adding the appended nodes to the *update* selection, modifying the contents of `sel`. This is described at length in my article [What Makes Software Good?](https://medium.com/@mbostock/what-makes-software-good-943557f8a488)

In v4, selections are immutable, so calling *enter*.append doesn’t silently change the contents of `sel`. Instead you have to explicitly merge enter and update if desired.

**Comment by trevithj** [comment]
Thanks for your patience. I know I missed the relevant sections in the docs. Thanks also for the article link. Showing the progression of the design thinking like that is really useful.

So to clarify, in order to get an *update-block* reference, I need to *run the enter() code first*, and call merge(...) on the result, passing in the original selection object. In other words, this is **good**:
````
var sel = d3.selectAll(...).data([...]);
var update = sel.enter().doAllCreationStuffHere().merge(sel);
````
Easier done than said :) The tricky bit is in making sure the enter() section has already run. That makes perfect sense now I think it through.
Thanks again for clarifying.

**Comment by mbostock** [comment]
Yup!
