### ISSUE TITLE
Include “xlink:” prefix when setting xlink attributes?

### ISSUE THREAD

**Issue by helguson** [d3/d3-selection#94]
### situation:

When using `selection.attr()` to set a `xlink:href`-attribute then the [namspace function](https://github.com/d3/d3-selection/blob/master/src/namespace.js)  detaches the `xlink:`-prefix.

When there is a SVG gradient like ...

``` SVG
<linearGradient id="gradient"/>
```

... and you apply ...

``` JavaScript
d3.select("#gradient")
    .attr("xlink:href", "#anotherGradient");
```

... then you get ...

``` SVG
<linearGradient id="gradient" href="#anotherGradient"/>
```

My Firefox 48.0.2 browser correctly renders this gradient on use ([try yourself](https://jsfiddle.net/96zL6ghn/)). 
### problem:

However the `xlink:`-prefix is part of the attribute name according to the [SVG standard](https://www.w3.org/TR/SVG/pservers.html#LinearGradientElementHrefAttribute). 

``` SVG
<linearGradient id="gradient" xlink:href="#anotherGradient"/>
```

... is more conform to the standard.

So the `xlink:`-prefix is missing when using `d3.attr()` to set the `xlink:href`-attribute for linear gradients of SVG.
### goal:

It is our goal to conform the SVG standard when creating SVG structures.
### proposal:

So I propose to include the `xlink:`-prefix into [the set of non-detachable prefixes that currently contains the `xmlns:`-prefix](https://github.com/d3/d3-selection/blob/master/src/namespace.js). Yet I don't know if it is useful to detach the `xlink:`-prefix in other places.

**Comment by mbostock** [comment]
You seem to be correct in that if you hand-author some static SVG embedded in HTML, like so:

```html
<svg width="960" height="500">
  <a xlink:href="http://example.com">
    <text x="20" y="20">Hello, world!</text>
  </a>
</svg>
```

The resulting A element has an attribute with name "xlink:href", prefix "xlink", and the XLink namespaceURI. Although strangely the same does not apply to other attributes with the xlink: prefix, such as “xlink:foo” (which has null as the prefix and namespaceURI). (Also in Chrome you can apparently omit the xlink: prefix and namespaceURI entirely, and it still works, but the same is not true of Safari and Firefox.)

However, if you try the same trick with a non-SVG element, you get the null prefix and namespaceURI again.

Related d3/d3#1935. I don’t see explicit [documentation in the DOM specification](https://www.w3.org/TR/dom/#dom-element-setattributens) that suggests we should treat xlink in the same manner as xmlns, so it makes me a bit nervous to change this behavior globally.

**Comment by Herst** [comment]
Safari still can"t do without it: https://bugs.webkit.org/show_bug.cgi?id=153854

**Comment by mbostock** [comment]
A workaround for this issue is to be explicit that “xlink” is both the namespace and part of the attribute name:

```js
d3.select("#gradient")
    .attr("xlink:xlink:href", "#anotherGradient");
```

**Comment by xdvarpunen** [comment]
@mbostock I had trouble with file-loader when setting href. Url is as string correctly, but when the url has number at start, the selection.attr method converts possibly url to number and adds decimals between the hash. Your solution of extra xlink: worked on that case too :) I don't know why.

**Comment by mbostock** [comment]
[xlink:href has been deprecated.](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) Use the explicit workaround (xlink:xlink:href) if you need it, and otherwise, avoid the namespace entirely.
