### ISSUE TITLE
Suggestion: would it be possible to allow for arrow function programming style?

### ISSUE THREAD

**Issue by Ptival** [d3/d3-selection#97]
Many d3 functions are built in a schema where one argument is passed via this-binding, while others are passed as parameters.

```
d3.selectAll(function(d, i nodes) {
  // this is bound to the DOM element
})...
```

As far as I can tell, there is no way to obtain the DOM element from the other arguments received by the function. This prevents a lexically-scoped programming discipline:

```
d3.selectAll((d, i nodes) => {
  // no way to access the DOM element...
})...
```

Would you envision catering for this style? A quick fix would be to always pass the "this" as an additional last argument.

(A nicer option would be to not do this-binding but heh...)

**Comment by mbostock** [comment]
You can access the element as `nodes[i]`. There are earlier discussions on this problem with fat arrow functions in the d3/d3 repo, if you’re interested. The short answer is that I can’t think of a good solution for this (other than the one I just mentioned, or avoiding fat arrows when you need to access `this`), especially one that would be backwards compatible.

**Comment by johyphenel** [comment]
Perhaps this could be specified in the documentation? Another example would be helpful to save falling into this trap. 

ex:
```
parent.each((p, j, g) => {
  // d3.select(this) doesn't work with arrow functions.
  d3.select(g[j])
    .selectAll(".child")
      .text(function(d, i) { return "child " + d.name + " of " + p.name; });
});
```
